### ISSUE TITLE
Can't run several packages

### ISSUE THREAD

**Issue by leoporoli** [kurtosis-tech/kurtosis#1035]
### What's your CLI version?

0.80.22

### Description & steps to reproduce

I get the same error (Kurtosis can't clone the package) when I try to run several packages:

```
There was an error interpreting Starlark code
Error in cloning git repository 'https://github.com/kurtosis-tech/postgres-package.git' to '/kurtosis-data/tmp-startosis-packages/tmp-repo-dir-2051142479/kurtosis-tech/postgres-package'. Make sure that 'https://github.com/kurtosis-tech/postgres-package.git' exists and is a public repository.
```

I tested with these packages:
- kurtosis run github.com/kurtosis-tech/postgres-package
- kurtosis run github.com/kurtosis-tech/eth2-package
- kurtosis run github.com/kurtosis-tech/eth-network-package

### Desired behavior

Kurtosis can clone the package and run it

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by adschwartz** [comment]
On it

**Comment by adschwartz** [comment]
This seems to be specific to @leoporoli machine. Closing.
