### ISSUE TITLE
Unable to get the tail of logs using `kurtosis service logs`

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1051]
### What's your CLI version?

0.80.23

### Description & steps to reproduce

When I do `kurtosis service logs blue-steppe cl-6-prysm-geth --tail 10`
I get: `Error:  unknown flag: --tail`

### Desired behavior

When I do `kubectl -n kurtosis-enclave--6f1b7974860846cda64438045b7eee69 logs -f cl-6-prysm-geth --tail 10`
I get the last 10 lines + follow logs. As expected. 

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by h4ck3rk3y** [comment]
@barnabasbusa Can you pipe the output of kurtosis service logs instead? That's what I do

`kurtosis service logs blue-steppe cl-6-prysm-geth  | tail -n 10` or `kurtosis service logs blue-steppe cl-6-prysm-geth  | tail -f`

**Comment by barnabasbusa** [comment]
`tail -n 10` works
`tail -f` doesn't seem to follow.

**Comment by h4ck3rk3y** [comment]
@barnabasbusa I just remembered service logs has `-f` flag as well. You could use that :). Let me know if that works!

**Comment by h4ck3rk3y** [comment]
Alright discussed with @barnabasbusa he wants the last ten lines and then follow whatever else comes.

**Comment by adschwartz** [comment]
Thanks @h4ck3rk3y. We'll leave this assigned to you

**Comment by h4ck3rk3y** [comment]
Pari from Eth echoe'd the need for this as well

**Comment by mieubrisse** [comment]
We also need this for Hyperlane; going to prioritize there

**Comment by leeederek** [comment]
Closed by #1341
