### ISSUE TITLE
Algolia Doc Search continuously breaking

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/kurtosis#1063]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/

### Issue description

DocSearch for most recent version of Kurtosis repeatedly breaks and requires search index to be refreshed.

![Screen Shot 2023-08-02 at 16 56 20](https://github.com/kurtosis-tech/kurtosis/assets/46531991/3c85db00-26b2-4f10-bed9-a7129e1c575b)

**Comment by tedim52** [comment]
- Investigate why is it's failing
- Assuming it's not easy to fix on our end: make a monitor to detect when it's broken and alert us

**Comment by mieubrisse** [comment]
Possible solution here: https://github.com/kurtosis-tech/kurtosis/issues/1238#issuecomment-1717414968

**Comment by mieubrisse** [comment]
We can fix both this and #1238 by just ripping out versioned docs
