### ISSUE TITLE
Retrieving enclave services fails with a large number of services

### ISSUE THREAD

**Issue by laurentluce** [kurtosis-tech/kurtosis#1074]
### What's your CLI version?

0.81.4

### Description & steps to reproduce

Commands or instructions retrieving a large number of enclave services fail.  This can also be seen when the Gateway starts.  The service network which sits in front of the backend only supports retrieving a single service which results in a large number of backend calls.  The K8S client rate limiter gets triggered.

### Desired behavior

Retrieving a large number of enclave services from the APIC should work with the help of a single call to the backend.

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by mieubrisse** [comment]
Probably related to #1050
