### ISSUE TITLE
Allow multiple services to be stopped with the same command

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1089]
### Background & motivation

Currently I can not stop more than one service at a time:
```sh
kurtosis service stop pristine-bay testnet-verifier prelaunch-data-generator-cl-genesis-data
Error:  accepts between 2 and 2 arg(s), received 3
```

### Desired behaviour

I should be able to stop as many services as I want with the same command. 
Also autocomplete the different services (that are not yet stopped).

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by ericobi** [comment]
I would like to work on this

**Comment by mieubrisse** [comment]
Thanks @ericobi ! It should be a very small change - just making the arg greedy

**Comment by mieubrisse** [comment]
Hey @ericobi , just wanted to follow up if you had a chance to look at this!

**Comment by leeederek** [comment]
@ericobi - hi did you have a chance to take a look at this?
