### ISSUE TITLE
Allow easily changing versions

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1098]
### Background & motivation

Two users now have needed to plug in forked/branch versions of a package, and it required them to go through every single `import_module` statement and update (which is a righteous pain).

### Desired behaviour

Users should only need to change the version in a single spot, BUT whatever solution we have shouldn't be annoying for users who want to quickly slam together a script.

SOLUTIONIZING: 
- Imports by default no longer require a `kurtosis.yml` (so that the "just slam a quick script together" usecase is still very easy (the user still does `kurtosis run .`). I think we can implement this by autogenerating a package name for the user, implicitly making the directory the user uploads a package).
- Packages on Github are still required to have a `kurtosis.yml` (and will always be required to have it)
- The `kurtosis.yml` file now has a place to specify dependencies and dependency versions
- We have a `kurtosis` command for adding dependencies & versions to the `kurtosis.yml` file

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by barnabasbusa** [comment]
It would be great to be able to  test out a PR like this:  https://github.com/kurtosis-tech/eth2-package/pull/120
The PR comes from a fork. The fork has all the references changed to the packages, but the PR itself only has the dashboard changes (which is what we should have). 
But the branch doesn't exist on the main repo, as its a pr from another fork.

You can't run that specific PR on top of upstream main right now.

**Comment by h4ck3rk3y** [comment]
Closing https://github.com/kurtosis-tech/kurtosis/issues/770 in favor of this issue

**Comment by leeederek** [comment]
@mieubrisse is going to take point on designing this with @leoporoli. This is related to #770 and #355 as well.
