### ISSUE TITLE
Always pull newest image

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1103]
### Background & motivation

When a new enclave is created, a trial attempt to fetch the latest images should be made.

This would ensure that someone is not spending endless time troubleshooting why an image not working, then realizing that the image is outdated already. 

### Desired behaviour

I want to always run the latest images at a certain tag.

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by mieubrisse** [comment]
Thanks for filing this @barnabasbusa ! How would you deal with the case where you've built a local version of an image that also exists on Dockerhub, and so pulling would overwrite your locally-built version?

**Comment by barnabasbusa** [comment]
Locally built images are nothing special. If someone wants to test a local image they can tag it with anything they want to ensure it doesn’t clash with the same tag as one ok dockerhub.

**Comment by mieubrisse** [comment]
Looking into this with @tedim52 ; I'd actually thought our current behaviour was to always try and pull the latest but seems like that's not the case

**Comment by parithosh** [comment]
Just an FYI: Usually most tools don't pull `latest` by default if an image tagged `latest` exists in the local registry (docker-compose for e.g). Its considered bad practice in production systems unless you add an `image_pull: true` or something to explicitly force that behavior. 

However, I see kurtosis as a testing system and its incredibly valuable for test setups to have the behavior of pulling latest by default. I'm fine with it being a flag and enabled in all runs by default, allowing prod setups to disable it. If kurtosis wants to focus more on prod users, then perhaps a `mode: test/prod` would achieve the same for this and future defaults. Just my 2c on the topic :)

**Comment by tedim52** [comment]
Thanks for weighing in here @parithosh ! We'll definitely keep that in mind as we address this : )

**Comment by mieubrisse** [comment]
Yep @parithosh , thinking along very similar lines here :) Ideally, everybody in the world would version-tag their images and follow proper GitOps of updating everything. In practice, many people use `latest` despite it being bad practice. We want Kurtosis to be able to handle dev, test, and prod equally (the "write your environment definition once" ideal), and enclave modes are probably our ticket here (e.g. "Prod"-like enclaves could have extra safeguards added to them).

We're only now starting to support the Prod usecase, so for now we might just make the "always try to pull the latest" default and in the future give a flag in Prod enclaves to flip it off

**Comment by mieubrisse** [comment]
Another datapoint to add (mostly for @barnabasbusa 's context): always pulling new images could potentially cause slowdowns and problems for folks who are offline, which is why we're doing some testing now to determine instead of immediately pulling the trigger

**Comment by barnabasbusa** [comment]
I'd like to see an option to disable always pulling, then none of the problems are real.

**Comment by mieubrisse** [comment]
Good morning @barnabasbusa ! Unfortunately we do have to contend with these problems still, because a new user coming along and thinking Kurtosis is slow isn't going to know why, or that a flag exists to make it faster. In many cases, our users aren't deeply familiar with Docker so the concept of image-pulling is somewhat hazy. With that said, Tedi's testing the speed right now in various cases, to see if we can get something that works for both your usecase and the general usecase. Stay tuned!

**Comment by mieubrisse** [comment]
Recording notes: in our call today, @barnabasbusa would prefer if this setting is in the config file so that when he tells new users how to run Kurtosis, he can give them the minimal line to copy-paste possible (e.g. `kurtosis run github.com/kurtosis-tech/eth2-package`)

**Comment by tedim52** [comment]
Hey @barnabasbusa ! After looking into this, we've determined that always pulling latest image shouldn't cause any significant slowdowns in Kurtosis, so we've gone ahead and implemented the functionality for ya! If users do start to exp some slowdown due to this, we may revert, but as of now should be out in the next release : )

**Comment by lostbean** [comment]
Feature re-added on #1495
