### ISSUE TITLE
Missing docs on using Kurtosis on remote infrastructure

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1108]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/k8s

### Issue description

Hey team, I'm learning more about how to use Kurtosis on remote infrastructure, and found the k8s docs helpful for getting started, but I am having trouble finding docs on the following:
- How the Kurtosis architecture looks like when on remote infrastructure?
- What the Kurtosis "portal" is - I've seen this in the changelogs but I don't know what it means.
- What a Kurtosis "context" is
- Instructions/guides on how to interact with the Kurtosis Engine and APIC with the CLI when working with enclaves in the cloud 

At a bare minimum, I would've expected some of these terms (portal, context) to be in the [glossary](https://docs.kurtosis.com/concepts-reference/glossary).

**Comment by leeederek** [comment]
Adding a few more:
- Glossary additions for `context`, `cluster`, `portal`
- CLI docs for `context` and `portal`
- Some info on what we use under the hood (architecture-wise)
- An explainer on *why* kurtosis cloud

**Comment by leeederek** [comment]
A user recently also asked: `btw is this one instance? or dynamically scaling kubernetes?` --> docs should help with questions like this going forward.

**Comment by laurentluce** [comment]
Running Kurtosis in Kurtosis cloud doc added in #1142
