### ISSUE TITLE
Add a `--args-file` flag to `kurtosis run`

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1112]
### Background & motivation

While reviewing the guidance around how to pass args to `run` from a file, I realized that the quoting/spaces thing is a hassle, especially for people unfamiliar with Bash. We can make this much easier for folks.

### Desired behaviour

We should add an `--args-file` option, so that the second argument to `kurtosis run` can be interpreted as a file, and read in as args for the user (no escaping or `"$(cat params.json)"` nonsense needed)

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
Extra reason we might want to do this: now that we have typehint comments in Starlark, we can actually allow users to treat Starlark packages like "CLIs", generating arguments. 

For example, let's say we had Starlark like so:
```python
def run(plan, image, optional_arg = "default"):
    """
    Args:
        image (string): The image that's needed
        optional_arg (string): Some optional arg
```
The GUI already uses this type-hinting information to generate a pretty form for users to fill in, and I'd like to do something similar in the CLI (so generating "args" and "flags" for the user). E.g.:
```bash
kurtosis run github.com/the-user/the-package "some-new-image" --optional_arg "New value of optional arg"
```

However, if we do this, we'll need to have a way for the user to say, "I have a JSON/YAML file, and each key of the root-level object is actually an argument"

**Comment by galenmarchetti** [comment]
+1 to this

**Comment by mieubrisse** [comment]
Requested again by Barnabas this morning (pain: it's difficult and annoying to remember the syntax)

**Comment by mieubrisse** [comment]
Also @leeederek had 3 people ask about this at Protocolberg, because the `"$(cat ...)"` syntax isn't cross-architecture (Windows does something different)

**Comment by h4ck3rk3y** [comment]
Abhi from web3-labs asked for this on Discord, I am on it
