### ISSUE TITLE
Remove sources of non-determinism from Starlark

### ISSUE THREAD

**Issue by victorcolombo** [kurtosis-tech/kurtosis#1120]
### What's your CLI version?

0.81.8

### Description & steps to reproduce

Despite one of the selling points of Starlark being determinism, it has on its standard library a source of non determinism:

https://pkg.go.dev/go.starlark.net/lib/time

`now() - Returns the current local time. Applications may replace this function by a deterministic one.`

This is causing problems on ETH package + idempotent runs

### Desired behavior

This function should be removed. Possibly replacements for it are plan primitive alternative (like we did with print) or push people to use the already existing primitives like exec or python. 

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by victorcolombo** [comment]
Slack context: https://kurtosistech.slack.com/archives/C051H93B6DV/p1690916576009869

**Comment by mieubrisse** [comment]
I'm upgrading this to "painful", as it prevents any package that uses this from being able to take advantage of idempotent runs
