### ISSUE TITLE
Incorrect pagination in Starlark reference Introduction page

### ISSUE THREAD

**Issue by abhiyana** [kurtosis-tech/kurtosis#1125]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/starlark-reference

### Issue description

I noticed that the bottom navigation (pagination) in the Starlark Reference Introduction page has a bug. The next page link points to the same Introduction page, instead of the Standard Library page. This makes it difficult to navigate through the documentation.

**Expected behavior:**
The next page link in the Introduction page should point to the Standard Library page.

**Actual behavior:**
The next page link in the Introduction page points to the Introduction page itself.

![image](https://github.com/kurtosis-tech/kurtosis/assets/47945971/0db555ef-c470-48aa-bcf5-b4492b6ab0d4)

**Comment by leeederek** [comment]
Hello @abhiyana! Thanks for letting us know. I've confirmed that this is indeed a bug and I'm going to look into this for you!

**Comment by omar711** [comment]
https://github.com/kurtosis-tech/kurtosis/pull/1499 fixes this one
