### ISSUE TITLE
bug: `create` and `connect` buttons in cloud.kurtosis.com do nothing 

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1126]
### What's your CLI version?

0.81.8

### Description & steps to reproduce

1. Open cloud.kurtosis.com
2. Log in
3. Click `create` or `connect` buttons on the sidebar

### Desired behavior

Selecting the `create` button on the sidebar creates an enclave. 

I'm not sure what the `connect` button should do, but i expect *something* to happen when i do click it

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by mieubrisse** [comment]
I believe @adschwartz is going to fix this soon

**Comment by mieubrisse** [comment]
Actually this is now working
