### ISSUE TITLE
Use more modern CPU arch in kurtosis cloud

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1127]
### Background & motivation

Kurtosis cloud currently uses t2.medium instances, which have a 32bit CPU. This FR is to change the instance type to a more modern CPU architecture

### Desired behaviour

Kurtosis cloud uses a compute backend that is more modern

### How important is this to you?

Must have

**Comment by h4ck3rk3y** [comment]
https://instances.vantage.sh/aws/ec2/t2.medium?selected=t2.medium. source of it being i386

**Comment by leeederek** [comment]
Logs from a user running eth2-package with besu client on cloud.kurtosis.com. The image being used is amd64 so obviously it doesn't work

```
  2023-08-18 09:12:45.685+00:00 | main | INFO  | Besu | Using the native implementation of the blake2bf algorithm
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  SIGILL (0x4) at pc=0x00007f2c9465906e, pid=8, tid=68
  #
  # JRE version: OpenJDK Runtime Environment (19.0.2+7) (build 19.0.2+7-Ubuntu-0ubuntu322.04)
  # Java VM: OpenJDK 64-Bit Server VM (19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
  # Problematic frame:
  # C  [libckzg4844jni.so+0x2606e]  __mulx_mont_384+0x4e
  #
  # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/besu/core.8)
  #
  # An error report file with more information is saved as:
  # /opt/besu/hs_err_pid8.log
  #
  # If you would like to submit a bug report, please visit:
  #   Unknown
  # The crash happened outside the Java Virtual Machine in native code.
  # See problematic frame for where to report the bug.
  #
  Aborted (core dumped)
```

**Comment by leeederek** [comment]
Also, nethermind/besu/erigon clients do not support 32bit arch cpus anymore, so this is a blocker for using those clients on the cloud

**Comment by leeederek** [comment]
Ethereum Mainnet spec will need 32GB/2TB/8c at least --> comment from a user

**Comment by mieubrisse** [comment]
I think this is done now, right @leeederek @adschwartz ?

**Comment by adschwartz** [comment]
We are now running on t3.medium and I verified they are not 32bit.
