### ISSUE TITLE
Remove old images of core and engine after upgrading to latest version

### ISSUE THREAD

**Issue by hemz10** [kurtosis-tech/kurtosis#1131]
### Background & motivation

Every time we update kurtosis to latest version the images of older version of engine and core remains. So there are multiple images of core and engine.
Is it possible to automatically remove older version after upgrading to latest version so that it doesn't occupy our disk space ?

### Desired behaviour

To remove old images of core and engine after upgrading to latest version. 

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by leeederek** [comment]
Thank you @hemz10! I wanted to ask: what kind of friction or pain points does this current behavior have on your workflow other than it occupying unnecessary disk space? 

This feature request makes a lot of sense to me,, but wanted to make sure I wasn't missing any context.

**Comment by hemz10** [comment]
Apart from that I don't see anything else that affects my workflow. I thought we could eliminate the manual work of removing old images :)

**Comment by mieubrisse** [comment]
Hey @hemz10 , nice idea! What do you think if `kurtosis clean` removed all versions of the engine that are older than the current version of the CLI being used?

**Comment by hemz10** [comment]
Hey @mieubrisse looks like a good idea as kurtosis clean command is something we will be using very often. But will it work with dive clean command as well ?

**Comment by mieubrisse** [comment]
if `dive clean` runs the Kurtosis clean under the hood, then yes!

**Comment by mieubrisse** [comment]
Implementation notes for the Kurtosian who takes this:
- I think we should implement this in the Clean endpoint on the Engine
- I'd suggest that calling the Clean endpoint should remove all _versioned_ (X.Y.Z) images of the APIC and Engine that are _older than the running Engine version_
- It should NOT remove newer versions, nor should it remove unversioned (i.e. dev) versions
- The Clean endpoint is called _very_ often (e.g. `kurtosis clean`), so the image-killing should be very fast (if it's slow, that's no good - we don't want to slow down `kurtosis clean` in any meaningful way)
