### ISSUE TITLE
`unix:///var/run/docker.sock` isn't found

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1140]
### What's your CLI version?

0.81.9

### Description & steps to reproduce

On some user machines (unknown what exactly causes this), there's no symlink at `/var/run/docker.sock`, pointing to the actual socket in the user's home directory (`~/.docker/run/docker.sock`). I'm not sure what causes this, and I've only seen it twice so far, but it MIGHT be related to installing Docker without `sudo`.

The bad news is, this is a confusing and hard blocker for users (especially those unfamiliar with Docker). This would have been a blocker for a user onboarding I was doing if I didn't know what the problem was (letting me guide the user to creating the symlink).

### Desired behavior

Regardless of whether `/var/run/docker.sock` exists, Kurtosis Just Works

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by marioevz** [comment]
I found a similar issue running in our hive server:
We have several user-dedicated `docker.sock` for multiple instances of the docker daemon running on the same host.
Each user has it defined as:
```
DOCKER_HOST=unix:///var/run/docker-marioevz.sock
```
It would be nice if this environment variable would be taken into account when running Kurtosis.

**Comment by mieubrisse** [comment]
Thanks @marioevz ! Sounds like #1072 would is very related to your issue

**Comment by mieubrisse** [comment]
@galenmarchetti hit this again yesterday after restart

**Comment by mieubrisse** [comment]
Seeing this again with a user. I'm starting to suspect that when Docker isn't installed via `sudo` mode, this is what happens

**Comment by mieubrisse** [comment]
We have a workaround: checking this value in the Docker engine config. However.... I don't want to call this a solution, because really Kurtosis should just handle both cases (whether `/var/run/docker.sock` is present or not)

![Screenshot_2023-09-19_at_16 52 22](https://github.com/kurtosis-tech/kurtosis/assets/1142185/97feba8b-36b6-49d3-88ac-7f9b9ab59184)
