### ISSUE TITLE
Improve SDK functionality and user experience

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1152]
### Background & motivation

There's a lot of boiler plating that needs to be done to get the SDK to run for example to run a simple package we have to produce this block

```
	// set up the input parameters
	logrus.Info("Parsing Input Parameters")
	inputParameters, err := os.ReadFile(inputFile)
	require.NoError(t, err, "An error occurred while reading the input file")
	require.NotEmpty(t, inputParameters, "Input parameters byte array is unexpectedly empty")
	inputParametersAsJSONString := string(inputParameters)
	require.NotEmpty(t, inputParametersAsJSONString, "Input parameter json string is unexpectedly empty")

	// set up enclave
	logrus.Info("Setting up Kurtosis Engine Connection & Enclave")
	ctx, cancelCtxFunc := context.WithCancel(context.Background())
	defer cancelCtxFunc()
	kurtosisCtx, err := kurtosis_context.NewKurtosisContextFromLocalEngine()
	require.NoError(t, err, "An error occurred while creating Kurtosis Context")

	enclaveName := fmt.Sprintf("%s-%d", enclaveNamePrefix, time.Now().Unix())
	enclaveCtx, err := kurtosisCtx.CreateEnclave(ctx, enclaveName)
	require.Nil(t, err, "An unexpected error occurred while creating Enclave Context")
	//defer kurtosisCtx.DestroyEnclave(ctx, enclaveName)

	// execute package
	logrus.Info("Executing the Starlark Package")
	packageRunResult, err := enclaveCtx.RunStarlarkRemotePackageBlocking(ctx, eth2Package, pathToMainFile, runFunctionName, inputParametersAsJSONString, isNotDryRun, defaultParallelism, noExperimentalFeatureFlags)
	require.NoError(t, err, "An unexpected error occurred while executing the package")
	require.Nil(t, packageRunResult.InterpretationError)
	require.Empty(t, packageRunResult.ValidationErrors)
	require.Nil(t, packageRunResult.ExecutionError)
```

One needs to know a lot of terms in order to get this going

1. What the KurtosisContext and engine's are
2. Enclaves
3. Enclave Creation before package execution
4. The RunRemoteStarlarkPackageBlocking call is very heavy on arguments - `pathToMainFile`, `runFunctionName`, `isNotDryRun`, `defaultParallelism`, `featureFlags` - this is a lot to digest and i put default empty values to get this going, this is frankly daunting for a new person looking at the SDK
5. After that is done you need to fetch the serviceContext, get public ports for them and only then you can start talking to the services

This is a lot of boiler plate to make an HTTP request to whatever is being spun up

### Desired behaviour

Ideally the SDK is much more simpler and has an API like

```
enclave.RunPackage(packageId, packageParams, ... PackageOptions)
```

The ...PackageOptions pattern is fairly common IMO and that should include everything that goes into `RunRemoteStarlarkPackageBlocking`.

If we could abstract away knowledge about engine / enclave creation that would be even nicer IMO

Hypothetically the PackageOptions could then contain fields like `EnclaveName` etc

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by mieubrisse** [comment]
Agreed. One very useful cleanup could be, pushing the `CreateEnclave` function [that we have inside our internal testsuite](https://github.com/kurtosis-tech/kurtosis/blob/main/internal_testsuites/golang/test_helpers/enclave_setup.go#L18), into the SDK itself. It's a VERY common usecase

**Comment by leeederek** [comment]
Related: https://github.com/kurtosis-tech/kurtosis/issues/843

**Comment by h4ck3rk3y** [comment]
Closing this as we have #843 being tracked separately
