### ISSUE TITLE
When `kurtosis cluster set docker` is run, but starting the engine fails, the `cluster-setting` file is set to emptystring

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1161]
### What's your CLI version?

0.82.4

### Description & steps to reproduce

The user had a firewall on their machine that meant that the engine container would start, but the engine healthiness check would fail. This would cause the `cluster set` to fail. Then, the `cluster-setting` file would get set to emptystring, which causes all sorts of chaos (related to https://github.com/kurtosis-tech/kurtosis/issues/1020 ).

### Desired behavior

Kurtosis should have no issues with any failures.

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by h4ck3rk3y** [comment]
Closed by https://github.com/kurtosis-tech/kurtosis/pull/1055
