### ISSUE TITLE
[Quality of Life] Add a way to list the available Services within an Enclave

### ISSUE THREAD

**Issue by zudsniper** [kurtosis-tech/kurtosis#1167]
### Background & motivation

I'm attempting to use the `@kurtosis-tech/autogpt-package` enclave with kurtosis engine 0.82.6 (latest on apt as of writing) and am encountering an interesting problem when trying to attach a service, as suggested [in the `README.md`](https://github.com/kurtosis-tech/autogpt-package#run-autogpt-on-your-machine), with    
  
```sh
$ kurtosis service shell autogpt autogpt
```  
> 🔵 The `kurtosis` enclave called `autogpt` is running -- I checked this with `kurtosis enclave ls` to ensure it was the case.   

#### **OUTPUT**  
![image](https://github.com/kurtosis-tech/kurtosis/assets/16076573/4e05543a-c63d-4947-b39a-c4179efe0cd5)

### Takeaways  
Through this use-case I have come to believe that it would benefit users to have a way to list the available service names for an enclave. Even if this enclave was created or configured incorrectly--which is likely the case--this functionality would facilitate locating/affirmatively identifying this problem. 

### Desired behaviour

my suggestion would be to add subcommands as follows

```sh
$ kurtosis service list <enclave>
```

this command would then produce an output which displays similarly to `kurtosis enclave ls`, providing as much or as little information about each service which is available -- so long as each services' name is included. I believe this would be helpful functionality, and though I haven't looked over the codebase, hopefully this is possible, and even better, not very complicated, to implement. 

---   

<sup> hi kurtosis team C: I've been away from developing much recently and haven't been around, but hopefully this will change and I can be an at least somewhat active member of your community. I still very much like the tool itself, and see significant potential. I hope you all are well since we last spoke. <br /><br /> Cheers, [`@zudsniper`](https://gh.zod.tf) </sup>

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
Hey @zudsniper , we actually have this already with `kurtosis enclave inspect`! Give it a spin and let me know how it goes

**Comment by mieubrisse** [comment]
Hey @zudsniper just wanted to check if this fixes your issue?

**Comment by zudsniper** [comment]
So sorry guys! I got what I needed totally out of `inspect`. My bad. Keep it real!
