### ISSUE TITLE
Running package from Create Enclave in Enclave Manager UI breaks

### ISSUE THREAD

**Issue by adschwartz** [kurtosis-tech/kurtosis#1176]
### What's your CLI version?

EM UI v. 2023-08-28-2

### Description & steps to reproduce

When you click Create Enclave and put in a package (e.g. github.com/kurtosis-tech/mongodb-package) the enclave is created but the streaming of the package run output back to the UI fails and it looks like the service is not created either. Only the enclave is created.

### Desired behavior

We should get the stream back into the EM UI

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by mieubrisse** [comment]
I haven't seen this in a while; closing for now
