### ISSUE TITLE
FR: print *all* logs when doing `kurtosis service logs` 

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1218]
### Background & motivation

Today `kurtosis service logs` prints only the first 200 lines in the terminal window. There are various workarounds for a user to get a specific log, including using the `-f` flag to tail the logs or the regex-match search flag. A user can also do a `kurtosis dump` but most users *expect* to see all the logs by default when using `kurtosis service logs`. 

### Desired behaviour

This FR is to remove the 200 line limit and print *all* logs when `kurtosis service logs` is used, with the newest logs last. Also make sure to update the docs here as well to reflect the change: https://docs.kurtosis.com/service-logs/

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by leeederek** [comment]
Relevant issue: https://github.com/kurtosis-tech/kurtosis/issues/1188

**Comment by mieubrisse** [comment]
Assigning to @Peeeekay and @tedim52

**Comment by leeederek** [comment]
Closed by #1341
