### ISSUE TITLE
missing future references in idempotent run

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1225]
### What's your CLI version?

0.82.18

### Description & steps to reproduce

```
# run this to completion
$ kurtosis run github.com/kurtosis-tech/eth-network-package@gyani/deterministic-time --enclave spooky-meadow
# run it again
$ kurtosis run github.com/kurtosis-tech/eth-network-package@gyani/deterministic-time --enclave spooky-meadow
```

![image](https://github.com/kurtosis-tech/kurtosis/assets/6670312/42879248-bb7b-42b9-a7b8-af1e88430785)

### Desired behavior

All instructions should be SKIPPED future reference shouldn't be lost

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by victorcolombo** [comment]
Rooted caused that we are indeed erasing this runtime value reference:

https://github.com/kurtosis-tech/kurtosis/blob/94a4b8bc5fc79b69845ab4493eb70307cf9d7b0f/core/server/api_container/server/startosis_engine/runtime_value_store/runtime_value_store.go#L61

During rerun, all instructions are skipped since there are no changes, but the return value contains a runtime value that is not present:
```

Starlark code successfully run. Output was:
[
        [
                {
                        "cl_client_context": {
                                "beacon_service_name": "cl-1-lighthouse-geth",
                                "cl_nodes_metrics_info": [
                                        {
                                                "name": "cl-1-lighthouse-geth",
                                                "path": "/metrics",
                                                "url": "{{kurtosis:0415c2adff3747129ef3020e20357ce5:ip_address.runtime_value}}:5054"
                                        },
                                        {
                                                "name": "cl-1-lighthouse-geth-validator",
                                                "path": "/metrics",
                                                "url": "{{kurtosis:7b16d5ddc9f747ca880d9beefc434b0f:ip_address.runtime_value}}:5064"
                                        }
                                ],
                               ...
]
```

**Comment by victorcolombo** [comment]
This was reproed with `0.82.16` so https://github.com/kurtosis-tech/kurtosis/pull/1170 did not caused it
