### ISSUE TITLE
updating image of `add_service` doesn't change the running service

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1226]
### What's your CLI version?

0.82.18

### Description & steps to reproduce

1. Clone the eth-network-package locally - checking out current main 30d2ccf8feae4fadc859a19c4a0697f2659cc90b
2. `kurtosis run . --enclave test`
3. Change https://github.com/kurtosis-tech/eth-network-package/blob/main/package_io/input_parser.star#L2 to `ghcr.io/paradigmxyz/reth` or `ethereum/client-go:v1.12.2-arm64`
4. `kurtosis run . --enclave test`

You will see that the package just runs fine and the image isn't updated in either the reth case or in the v1.12.2-arm64 case. 

### Desired behavior

I'd expect `reth` to not start as flags would be wrong, and for `v1.12.2-arm64` I'd expect this image in `add_service`

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by leeederek** [comment]
+1, i just experienced this too. This is a blocker for using idempotent runs with the eth2-package.
