### ISSUE TITLE
Support linting Stalark packages

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1228]
### Background & motivation

https://github.com/kurtosis-tech/eth-network-package/pull/54
https://github.com/kurtosis-tech/eth2-package/pull/109

We don't have liniting

### Desired behaviour

We want something like

`kurtosis lint .`
`kurtosis lint /path/to/file.star`

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by mieubrisse** [comment]
IMO, UX should be:
`kurtosis lint .` (if you pass in a directory, we recursively search for all `.star` files and lint them according to Kurtosis Starlark rules)
`kurtosis lint something.star` (if you pass in a Starlark file, you'll lint just that file)
`kurtosis lint . something.star something-else.star` (you can pass in multiple files and directories and Kurtosis will apply all linting rules to each of them)

Documentation note: the docs should have very clear description of what linting rules we're using. The ideal is that we're purely calling down to another very-well-established linter, so users who are familiar with that linter can just use those rules. This gives the extra benefit of, we don't need to build exclusion rules (e.g. `# linter-ignore: blahblahblah`) by hand

**Comment by h4ck3rk3y** [comment]
@mieubrisse Agreed on the above!

**Comment by h4ck3rk3y** [comment]
- [x] convert asser to verify PR
- [ ] release the `docker` version In Progress
- [ ] support pooling + release the KT version
