### ISSUE TITLE
Make update cli message a one liner

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1244]
### Background & motivation

Its a nitpick issue: 

Instead of 
```sh
WARN[2023-09-06T13:14:03+02:00] You are running an old version of the Kurtosis CLI; we suggest you to update it to the latest version, '0.82.19'
WARN[2023-09-06T13:14:03+02:00] You can manually upgrade the CLI tool following these instructions: https://docs.kurtosis.com/install#upgrading
```

### Desired behaviour

Do something like this: 
```sh
WARN[2023-09-06T13:14:03+02:00] You are running an old version of the Kurtosis CLI; we suggest you to update (https://docs.kurtosis.com/install#upgrading) it to the latest version, '0.82.19'.
```

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
Strongly agree; see also https://github.com/kurtosis-tech/kurtosis/issues/1130#issuecomment-1686813023

**Comment by leeederek** [comment]
Thanks @barnabasbusa, this seems like a reasonable ask to me!
