### ISSUE TITLE
talk about @ imports in import_module so that people can pin versions

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1255]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/starlark-reference/import-module/

### Issue description

Solves the JustFarming issues

**Comment by leeederek** [comment]
Thanks @h4ck3rk3y i'll work on this.

**Comment by tomknig** [comment]
Thanks for tracking this issue. I do agree that adding documentation around pinned versions will be helpful.
We've successfully implemented pinned versions in our project here: [justfarming/contracts#3](https://github.com/justfarming/contracts/pull/3)
