### ISSUE TITLE
bug: "Newer Kurtosis version" message not printing when there's a new version available

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1258]
### What's your CLI version?

0.82.17

### Description & steps to reproduce

I'm seeing from the monorepo that 0.82.21 is released and I'm on 0.82.17, but I'm not seeing any "new Kurtosis version available" message getting printed:
```
$ kurtosis version
CLI Version:   0.82.17

To see the engine version (provided it is running): kurtosis engine status
$ kurtosis enclave ls
UUID           Name        Status     Creation Time
8cfaab9ebf62   hyperlane   RUNNING    Thu, 07 Sep 2023 13:10:24 -03
```

### Desired behavior

I should get the "new Kurtosis version available" message printed when there's a new version available

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by leeederek** [comment]
Hey @mieubrisse, the current behavior in Kurtosis is to check the versions and warn users if there is a different *at most once per hour* as per #224. See my screenshot below alongside the timestamps:

```
Last login: Thu Sep  7 14:46:57 on ttys002
WARN[2023-09-07T14:46:57-04:00] You are running an old version of the Kurtosis CLI; we suggest you to update it to the latest version, '0.82.21'
WARN[2023-09-07T14:46:57-04:00] You can manually upgrade the CLI tool following these instructions: https://docs.kurtosis.com/install#upgrading
➜  ~
Last login: Thu Sep  7 14:49:57 on ttys000
➜  ~ kurtosis version
CLI Version:   0.82.19

To see the engine version (provided it is running): kurtosis engine status
```

The next time/hour you try to use Kurtosis, you should see the WARN line. Let me know if this answers your question or if you'd like to suggest a Feature Request. Thanks!

**Comment by mieubrisse** [comment]
Ahh okay, I must have missed it during this hour then
