### ISSUE TITLE
docs: add more details/examples for using templates and template variables

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1261]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/starlark-reference/plan/#render_templates

### Issue description

We got feedback from a user that the concept of using templates and template variables was difficult to grok. This issue tracks the changes (potentially beyond just docs) that would help us bridge this knowledge gap.

**Comment by mieubrisse** [comment]
I agree with this FWIW. And most of the times, the user doesn't actually need template-rendering. We've discussed having a `store_strings` command that creates a files artifact from future-reference-replaced string values; this would probably fix 90% of user issues.

**Comment by mieubrisse** [comment]
Ton more history: https://github.com/kurtosis-tech/kurtosis-private/issues/751
https://www.notion.so/kurtosistech/Build-store_strings-3b8f68ef32034c709bdceca03f334266?pvs=4

**Comment by mieubrisse** [comment]
Opened #1333 to give users an option that's not as heavyweight/annoying as templates

**Comment by h4ck3rk3y** [comment]
@galenmarchetti fixed this recently
