### ISSUE TITLE
docs: its unclear to me when to use the "explanations" and "concepts reference" pages while in the docs

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1287]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/

### Issue description

When navigating the various topics about Kurtosis, it is confusing to me what the differences were between the [`explanations`](https://docs.kurtosis.com/explanations/why-we-built-kurtosis) and [`concepts reference`](https://docs.kurtosis.com/concepts-reference/enclaves) pages.

**Comment by mieubrisse** [comment]
Agreed; @galenmarchetti is thinking heavily about this. I'm now of the opinion that the current breakdown of the lefthand sidebar isn't great
