### ISSUE TITLE
FR: print and persist ALL the downloaded container image tags on each run

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1292]
### Background & motivation

Today, on every Kurtosis run at the validation step, the image tags that get pulled are printed in the command line _only if the images do not exist locally:_
<img width="1209" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/c5a18912-ff87-4528-8d70-6b4d836e7fe4">

But after they are downloaded, the text disappears. I would like to know, on each run, that Kurtosis is using the image tags I expected and so this would allow me to cancel the run earlier if I see that Kurtosis is using an image tag that I didnt expect.

### Desired behaviour

This Feature Request is to track a few improvements as requested by Barnabas:
1. Persist the log lines that read `"Downloading ethpandaops/etheruem-genesis-generator:2.0.0-rc6"` when Kurtosis is downloading the image. Right now, they disappear after a while.
2. When the download is complete, update the line with: `ethpandaops/etheruem-genesis-generator:2.0.0-rc6 download complete.`
3. Show *ALL* the image tags - right now, Kurtosis only prints 4 lines max but if I am using 7 images, I want to see Kurtosis download all 7 and show that the downloads are complete.

When the image is built locally, I do not expect to see Kurtosis say anything about those image tags.

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by barnabasbusa** [comment]
It would be a nice to have feature to see what images are fetched at launch and what is not. 

Its a good sanity check!

**Comment by mieubrisse** [comment]
Hey @barnabasbusa @leeederek , the exact images being used are actually already available as the `image` tag of each command!

<img width="1247" alt="Screen Shot 2023-09-13 at 12 56 01" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/257a0d4f-dc95-4caa-becc-fce0f25fa575">

**Comment by barnabasbusa** [comment]
Indeed it is. 

The idea was to have it all in one place on the top of the command (as it already shows up, just disappears as soon as the images are downloaded).

**Comment by leoporoli** [comment]
@barnabasbusa I'm working on a solution for this and I wanted to ask you if this will give you what you need.

We can print some kind of "summary info" after all images are pulled (from the cloud or locally)



![Image](https://github.com/kurtosis-tech/kurtosis/assets/29951623/ccb25b2d-4485-4160-88bd-f43e60b09fa0)

Does it work for you?
