### ISSUE TITLE
-f flag is broken for logs; it doesn't spit out new logs

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1293]
### What's your CLI version?

0.82.22

### Description & steps to reproduce

1. kurtosis run github.com/kurtosis-tech/eth2-package
2. kurtosis service logs murky-peak cl-1-lighthouse-geth -f
3. kurtosis service logs murky-peak cl-1-lighthouse-geth -f (in a different terminal after a minute)

You will see 2 & 3 have different logs and 2 isn't actually tailing

### Desired behavior

kurtosis service logs murky-peak cl-1-lighthouse-geth -f

is actually tailing

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by tedim52** [comment]
Addressed in #1298
