### ISSUE TITLE
Allow offline mode with local images

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1299]
### Background & motivation

I know I have requested a feature to always pull images, however, it would be great if there would be a mode where this would not be enabled by default.

### Desired behaviour

It would be great if there would be a flag e.g: `--offline` which disabled all image pulls and only works with local images.

Basically to allow kurtosis to operate in an offline only mode. (Very useful when your internet connection is unreliable, and you know that you already have the images locally available). 

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by mieubrisse** [comment]
Hey @barnabasbusa , I'm keen to grab a chat with you to see explicitly what were the symptoms you experienced. I think there's the opportunity to put some smart logic in the product

**Comment by mieubrisse** [comment]
Related to, but not superseded by, #1307

**Comment by h4ck3rk3y** [comment]
hey @mieubrisse I have assigned this to you as Tedi told me there's some design work going on on this;

**Comment by leeederek** [comment]
Hey @barnabasbusa, we've merged #1495 and #1660! Kurtosis can now be used while offline so long as your images are locally cached. By default, Kurtosis will not attempt to fetch new image tags if an image already exists locally. 

Can we close out this issue?
