### ISSUE TITLE
Change kurtosis engine status to kurtosis engine version

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1309]
### Background & motivation

This to to make it consistent with `kurtosis version` command.

### Desired behaviour

Have `kurtosis engine version` working. 

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
Thinking about this, I'm not actually sure we want to do this. Rationale: if we make it `kurtosis engine version`, then if we add any other sort of information about the engine (e.g. disk usage, CPU usage, etc.) then we would have to add a new `kurtosis engine` subcommand. It's annoying that `kurtosis version` != `kurtosis engine status`, but I thiiiiiink the extra entropy might be right in this case
