### ISSUE TITLE
[bug]: `kurtosis clean -a` only prints the name of *some* enclaves, not all.

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#133]
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.68.5

### (Optional) What is your metrics user ID?

07d14724970e58810d93e5520436603ca4c113ad9bd608bec371f9122534cf4b

### What is the severity of this bug?

Papercut, this bug is frustrating, but I have a workaround.

### Description & steps to reproduce

When I have many enclaves and run `kurtosis clean -a`, I see that Kurtosis removes both running and stopped enclaves and prints out their UUID and name. However, I noticed that not all of the enclave names got printed (even though the removed enclave UUIDs got printed). See screenshots below.

I had many running enclaves:
<img width="811" alt="Screenshot 2023-03-09 at 4 26 27 PM" src="https://user-images.githubusercontent.com/103802618/224161361-3c68b3cc-3265-413f-82f2-44fa4d0aadb7.png">

But when I ran `kurtosis clean -a`, it only printed the names of _some_ of the enclaves that were removed:
<img width="1100" alt="Screenshot 2023-03-09 at 4 26 51 PM" src="https://user-images.githubusercontent.com/103802618/224161473-289fd1e6-bf12-4fac-b61d-3e0646675021.png">

### Relevant log output

See screenshots above.

### Desired behavior

I would expect that everytime I run `kurtosis clean -a`, both the UUID and name of all removed enclaves will get printed for me.

**Comment by h4ck3rk3y** [comment]
I think I know what's going on. You restarted Kurtosis engine and the other enclave names that are missing were from before the restart.

We don't persist enclave identifiers. We could persist the uuid / name mapping in a database and that would solve the problem & enable name / uuid translations post restart for other features. But this is probably a few hours of engineering work. Do you think this is painful enough? Or could we put "Not Available" for now; that is a few minutes of work.

**Comment by mieubrisse** [comment]
@gbouv this is relevant for your design on Kloud, as you were mentioning relying on the fact that the engine is stateless (and it very likely won't be).

**Comment by leeederek** [comment]
Thank you @h4ck3rk3y for the quick response! I was able to reproduce the bug and confirmed that this does indeed happen when you run `kurtosis clean -a` on a recently restarted engine. Enclaves created prior to the restart operation will still be running but their enclave names are gone. 

How are the enclave UUIDs persisted then? Is it because those details are still available in my docker VM for Kurtosis to pull from and print?

**Comment by h4ck3rk3y** [comment]
@leeederek The enclave uuid & name mappings are persisted in memory in a map. If you restart the Kurtosis engine all of the volatile memory gets lost and we lose the Name -> UUID mappings, leading to the behavior that you ran into.

**Comment by h4ck3rk3y** [comment]
This has been fixed and will be released with Kurtosis 0.68.8

**Comment by leeederek** [comment]
Thanks @h4ck3rk3y , what was the fix? Did you decide to persist the name<>UUID mappings even after engine restarts?

**Comment by h4ck3rk3y** [comment]
We already persist the name / uuid bits in the container engine (thats how enclave ls works post restart). Before the cleanup I just prefetch the mappings; and then let the cleanup happen
