### ISSUE TITLE
Support private container registries

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1342]
### Background & motivation

An occasional, but persistent, request we get is for supporting private container registries. We've been able to get by with only public registries so far, but we should have a way to support them.

This also ties in with handling secrets, as the secrets Kurtosis stores to access private repositories/registries need to be stored securely.

### Desired behaviour

Kurtosis has a way to access private container registries.

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

**Comment by leeederek** [comment]
Closing as duplicate of #1269

**Comment by mieubrisse** [comment]
Not a duplicate; #1269 is for private Github repos while this is for private container registries. Related problems, but separate

**Comment by franjoespejo** [comment]
nice to have for us at Shamir Labs, but not critical since we can always download the private images locally
