### ISSUE TITLE
[FR]: Sort services in `enclave inspect` by service creation time

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#135]
### Background and motivation

Right now the current `enclave inspect` output sorts services on their UUID, which leads to crazy sorts:

<img width="460" alt="Screen Shot 2023-03-09 at 15 56 12" src="https://user-images.githubusercontent.com/1142185/224197062-2551c572-8578-4400-a6ad-81076e7dbeb7.png">

It would be reasonable to sort based on the service creation time

### Current behavior

Sort by UUID

### Desired behavior

Sort by service creation time

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by leeederek** [comment]
Sorting by name (#139) is likely good enough here and I'm in favor of closing this out. @mieubrisse, do you agree that the changes made in #139 address this pain point, even though the implementation is different (sorting by name instead of creation time).

**Comment by mieubrisse** [comment]
Fine for now, though I do think sorting by creation time will become more important when we have bigger enclaves
