### ISSUE TITLE
[FR]: Make the `kurtosis feedback` command guide users to easier ways of feedback

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#137]
### Background and motivation

I expected `kurtosis feedback` to guide me in filing feedback. However, I just got the display with the links. If I hadn't seen the feature get built, I wouldn't know that:

1) you can pass in flags to go directly to the feedback
2) I should even pass in `-h` to see what those flags are
3) I can type a message as the first argument to auto-populate it

(Also, quick aside, but the message I type in for Github gets discarded)

### Current behavior

`kurtosis feedback` prints a block of text with links

### Desired behavior

Running `kurtosis feedback` guides me to giving feedback in easier ways (flag, passing in the message)

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by leeederek** [comment]
Hey @mieubrisse! This is great feedback. I'd like to propose a quick prototype to get your thoughts:

What if when you ran `kurtosis feedback -h`, the CLI would respond with:

> Give feedback, file a bug report or feature request, or get help from the Kurtosis team. See below for the many ways you can get in touch with us.
>
> TIP: You can quickly type and send us feedback directly from the CLI. For example, `kurtosis feedback "I enjoy the enclave naming theme"` will open an email draft to feedback@kurtosistech.com with the message pre-filled with _"I enjoy the enclave naming theme"._ 

Adding this tip will help guide the user to send us feedback. What do you think?

**Comment by mieubrisse** [comment]
Hey @leeederek , I like the idea of adding more info to the helptext but I think the problem is that it's not obvious to a user why they'd run `kurtosis feedback -h` (because `kurtosis feedback` does a thing that doesn't take in any args or flags)

**Comment by leeederek** [comment]
Cool @mieubrisse! My understanding then is that you're asking for more explicit nudges or tips of some kind for a user to easily see what flags and args they can use with the `kurtosis feedback` command. Is that correct?

Prototype: when running the `kurtosis feedback` command, the following message gets printed:

> =====================================================
||          Your feedback is valuable and helps us improve Kurtosis. Thank you.          ||
=====================================================
> This command can be used to deliver feedback to the Kurtosis team! 
> * Pass in your feedback as an argument using double quotations (e.g. `kurtosis feedback "my feedback"`).
> * Pass in the `--github` flag to open our Github Issues templates, pre-filled with your feedback/arg.
> * Pass in the `--email` flag to open a draft email, pre-filled with your feedback/arg, to send to feedback@kurtosistech.com. 
> * Pass in the `--calendly` flag to open our Calendly link to schedule a 1:1 session with us for feedback and questions you may have!

> See below for the some direct links as well.

> * For bugs/issues, let us know in our Github.
> * For general feedback, click here to email us.
> * If you need help getting started, schedule an on-boarding session with us.

What do you think?

**Comment by leeederek** [comment]
Stale, closing
