### ISSUE TITLE
ensure that docker engine is running when running lint

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1375]
### What's your CLI version?

0.83.5

### Description & steps to reproduce

Run `kurtosis lint . --format` when docker engine isn't up you will get an exit code 125 and a message that its a bug in Kurtosis. 

### Desired behavior

We account for docker engine being down and return a suitable message

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by omar711** [comment]
fixed by https://github.com/kurtosis-tech/kurtosis/pull/1506
