### ISSUE TITLE
Bad gateway screen in Kurtosis cloud interface

### ISSUE THREAD

**Issue by leoporoli** [kurtosis-tech/kurtosis#1382]
### What's your CLI version?

0.83.6

### Description & steps to reproduce

I went to `https://cloud.kurtosis.com` and the first screen I saw was this:
<img width="1392" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/29951623/e3538c0b-b988-4e90-ad4a-fb3a1e4630b4">

### Desired behavior

It was fixed when I went to the connect section and run the suggested commands, probably the fix could probably be going directly to to `https://cloud.kurtosis.com/connect` first instead of `https://cloud.kurtosis.com/enclave-manager`

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by adschwartz** [comment]
@leoporoli my guess is that the engine was dead on that box. Did the prompt write any error messages after you ran the connection commands?

**Comment by adschwartz** [comment]
Marking this as done. @leoporoli feel free to reopen if you have more issues
