### ISSUE TITLE
The package catalog/configuration screen has no way to go back to the enclave list

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1388]
### What's your CLI version?

0.83.7

### Description & steps to reproduce

When I go to the package catalog screen, I can't back out (not even by clicking 'Enclave Manager' on the left):

<img width="1299" alt="Screen Shot 2023-09-26 at 13 21 35" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/19f87641-03a3-4e2e-8fe8-2d21bbe447a7">

### Desired behavior

I have a way to get back to my enclave list

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by tedim52** [comment]
Upcoming redesign of package catalog fixes this issue.
