### ISSUE TITLE
Formatting the `agent_config.json` expands the display off the edge of the screen with no scrollbar

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1389]
### What's your CLI version?

0.83.7

### Description & steps to reproduce

<img width="1278" alt="Screen Shot 2023-09-26 at 13 23 40" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/04cdc7e6-6ec1-4e91-b84c-3cb0b453d525">

### Desired behavior

I get a scrollbar to scroll through file contents after formatting

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by Peeeekay** [comment]
@adschwartz I believe you are already on it - it's similar to not being able to scroll on ServiceInfo page ( assigning this to you). This happens with CodeEditor component.
