### ISSUE TITLE
Kurtosis Logs not being cleaned

### ISSUE THREAD

**Issue by cbermudez97** [kurtosis-tech/kurtosis#1394]
### What's your CLI version?

0.83.5

### Description & steps to reproduce

When running a package multiple times, and later removing the enclave( or running `kurtosis clean -a`) looks like the contents of the `kurtosis-logs-storage` volume related to previous runs are not correctly cleaned. This can lead to these volumes consuming high amounts of disk space especially when running with a high number of services(ie. https://github.com/kurtosis-tech/eth2-package).

Steps to reproduce:
1. Run `kurtosis run github.com/kurtosis-tech/eth2-package`.
2. Wait for the execution to finish.
3. Delete enclave through either `kurtosis enclave [stop|rm] <name>` or `kurtosis clean -a`
4. Restart from step 1. multiple times

<img width="332" alt="Screenshot 2023-09-26 at 12 41 34 PM" src="https://github.com/kurtosis-tech/kurtosis/assets/43155355/1f6de74a-42dc-4d28-ba8e-02c194e2fc5d">
<img width="637" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/43155355/82810499-f5aa-4dbe-93ae-ccd62139e537">

### Desired behavior

Removing an enclave with either `kurtosis enclave rm <name>` or `kurtosis clean -a` should also remove logs stored on the `kurtosis-logs-storage` volume. Otherwise, a flag or command should be able to clean it more easily.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by tedim52** [comment]
Hey @cbermudez97. Thanks for creating this issue! Assigning this to myself and looking into it. I'll get back to you once I've got smth : )

**Comment by tedim52** [comment]
Hey @cbermudez97 just merged this fix along with some other things that will reduce logs storage. This should be out in the next kurtosis release so I'll ping you then so you can upgrade!

**Comment by tedim52** [comment]
Hey, @cbermudez97 the fix is released in [`v0.84.3`](https://github.com/kurtosis-tech/kurtosis/releases/tag/0.84.3) if you want to update. Will note that this only applies to future logs created - so if you want to free up current logs, I recommend manually removing the `kurtosis-logs-storage` Docker volume to get rid of old logs and start fresh. (if you don't need them of course)
