### ISSUE TITLE
docs: add more details about what clean *actually* does

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1396]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/clean/

### Issue description

`kurtosis clean` does more than what the docs illustrate. This issue is to track additions to the docs to ensure we communicate properly what `kurtosis clean` actually does under the hood when its used.

What the docs currently say:
- removes stopped enclaves (and live ones when `-a` flag is used) and stopped engine containers

What the command *actually does*:
- removes stopped enclaves and stopped engine containers (and if the `-a` flag is set, all running enclaves + engine containers will also be removed)
- removes all services within enclaves
- removes all unused kurtosis images (engine + logs aggregator + enclaves)
- removes all files artifacts and all docker volumes within those enclaves

**Comment by leeederek** [comment]
Related: https://github.com/kurtosis-tech/kurtosis/pull/1349

**Comment by chunha-park** [comment]
Changes have been made, closing!
