### ISSUE TITLE
When service logs scrollbar is at the bottom, new logs are silently added below

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1399]
### What's your CLI version?

0.83.7

### Description & steps to reproduce

1. Open the relayer service logs
2. Scroll the scrollbar to the bottom (necessary because of #1392 )
3. Wait for new logs to come in
4. New logs don't result in the scrollbar scrolling

This is a problem because the user doesn't realize there are new logs coming in

### Desired behavior

The scrollbar being at the bottom should mean that new logs appear automatically

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by tedim52** [comment]
Service logs display redesign fixes this.
