### ISSUE TITLE
Clicking relayer logs leaves the scrollbar halfway up

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1403]
### What's your CLI version?

0.83.7

### Description & steps to reproduce

https://www.loom.com/share/2a6ba22a3f2e42af91ef4fcfcd37690c

Means the user has to manually scroll to the bottom or click the scroll-to-bottom button whenever they view the logs.

My guess is this appears when there are a lot of logs

### Desired behavior

When clicking the logs, the scrollbar is already at the bottom

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by mieubrisse** [comment]
Same thing is happening on the Starlark output. Here, I'm confused why there are no new logs, and it turns out the scrollbar wasn't at the bottom:

https://www.loom.com/share/6d692e4a352e4b90a878fa2353d9572e @ 0:15

**Comment by mieubrisse** [comment]
FWIW it _doesn't_ seem to be happening on the service logs anymore

**Comment by tedim52** [comment]
Service logs redesign with new scroll should've fixed this
