### ISSUE TITLE
URLs to hosts and exposed ports in kurtosis web local interface

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis#1414]
### Background & motivation

I want to use Kurtosis Web to be able to easily click into my running enclaves and then click into my services with exposed ports

### Desired behaviour

I'd like to have a screen in the enclave, or in a service view, where the exposed ports+hosts are rendered as a clickable URL

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by leeederek** [comment]
Hi @galenmarchetti - thanks for filing this issue. Just to make sure I follow along completely: 

Are you referring to the exposed port in the "port" section in the enclave manager UI and the fact that you'd like for that to be a clickable URL from the get-go?
<img width="1983" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/a0cccb3b-cd59-4c70-9097-04f2c7d091f1">

**Comment by leeederek** [comment]
Hey @galenmarchetti - as of 0.85.6 for Kurtosis Cloud enclaves spun up using the CLI, ports are now forwarded properly and can be navigated to from the UI. Closing this out!
