### ISSUE TITLE
docs: rename all mentions of `eth2-package` and `eth-network-package` to ethereum-package

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1415]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/how-to-local-eth-testnet

### Issue description

Rename/update all mentions of eth-network-package and eth2-package to ethereum-package, including links:
- https://docs.kurtosis.com/how-to-local-eth-testnet
- https://docs.kurtosis.com/how-to-compose-your-own-testnet
- https://docs.kurtosis.com/how-to-full-mev-with-eth2-package
- https://docs.kurtosis.com/quickstart
- https://github.com/kurtosis-tech/awesome-kurtosis#kurtosis-web3-starlark-packages

and probably other places

**Comment by chunha-park** [comment]
https://github.com/kurtosis-tech/kurtosis/pull/1443 pending review!
