### ISSUE TITLE
The files artifact content display does not preserve newlines

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1417]
### What's your CLI version?

0.83.7

### Description & steps to reproduce

Python file that gets uploaded:

![image (2)](https://github.com/kurtosis-tech/kurtosis/assets/1142185/7e963783-f823-4338-af53-138ade8f7015)

What gets displayed:

![image (1)](https://github.com/kurtosis-tech/kurtosis/assets/1142185/bbde8b74-6bf6-4353-a5ba-02a0d5fa38fc)

### Desired behavior

The display in the EM looks exactly like what was uploaded

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by mieubrisse** [comment]
90% sure the problem is here: https://github.com/kurtosis-tech/kurtosis/blob/main/core/server/api_container/server/api_container_service.go#L825

**Comment by h4ck3rk3y** [comment]
This is the same bug as https://app.zenhub.com/workspaces/engineering-636cff9fc978ceb2aac05a1d/issues/gh/kurtosis-tech/kurtosis/1042
