### ISSUE TITLE
EM reporting "No logs available" when logs are actually available

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1439]
### What's your CLI version?

0.83.14

### Description & steps to reproduce

https://www.loom.com/share/6d692e4a352e4b90a878fa2353d9572e?sid=01581687-e7f9-4e91-ac8c-67990162c568 @ 5:32

### Desired behavior

The EM accurately reports whether logs are available or not

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by tedim52** [comment]
Fixed by https://github.com/kurtosis-tech/kurtosis-cloud-gateway/commit/022d9cb18343b51809b639c903a25543e362e244
