### ISSUE TITLE
`blob-spammer` CMD is allowing vertical scroll for some reason

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1440]
### What's your CLI version?

0.83.14

### Description & steps to reproduce

https://www.loom.com/share/6d692e4a352e4b90a878fa2353d9572e?sid=338631dc-227a-451f-b2c9-88b94a5dc014 @ 6:34

For some reason, the CMD (even though it completely fits in the display) still allows for one line of vertical display. The other blocks don't do this.

Maybe it's because the CMD is so long??

### Desired behavior

Since the CMD completely fits on the screen, it doesn't have any vertical scrolling at all (and it doesn't capture any scrolling per #1438 )

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by adschwartz** [comment]
I believe this is fixed with the release of https://github.com/kurtosis-tech/kurtosis/pull/1452. @mieubrisse let me know you are still seeing this and we can re-open. I wasn't able to reproduce this issue after mouse wheel capture for vertical scrolling was turned off.
