### ISSUE TITLE
old package

### ISSUE THREAD

**Issue by franjoespejo** [kurtosis-tech/kurtosis#1467]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/quickstart/#spin-up-your-system

### Issue description

``kurtosis run --enclave eth-network github.com/kurtosis-tech/eth2-package "$(cat ~/network_params.json)"``

returns:
`There was an error interpreting Starlark code 
Error occurred while validating /kurtosis-data/startosis-packages/kurtosis-tech/eth2-package/kurtosis.yml
	Caused by: The package name in kurtosis.yml must match the location it is in. Package name is 'github.com/kurtosis-tech/ethereum-package' and kurtosis.yml is found here: 'github.com/kurtosis-tech/eth2-package'
`

It should be replaced by
``kurtosis run --enclave eth-network github.com/kurtosis-tech/ethereum-package "$(cat ~/network_params.json)"``

**Comment by leeederek** [comment]
Hey @franjoespejo ! Thank you for filing this issue. We're tracking to fix this here: https://github.com/kurtosis-tech/kurtosis/pull/1443, will get this merged by EOD :)
