### ISSUE TITLE
docs: update all guides to use new `--args-file` flag

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1468]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/run#extra-configuration

### Issue description

The new `--args-file` flag for `kurtosis run`, released in 0.83.16 is great - let's update all our docs to use this flag anytime a `kurtosis run` is mentioned with an args file.

**Comment by mieubrisse** [comment]
Yesssssssssssss. https://github.com/kurtosis-tech/package-template-repo could be updated too if you want!
