### ISSUE TITLE
Port mapping configuration to 127.0.0.1

### ISSUE THREAD

**Issue by OlegJakushkin** [kurtosis-tech/kurtosis#1475]
### Background & motivation

I want to be sure that a given service exposes to host a special, known (or configured on launch) port. Say a debugger exposes 40000 in docker and I want to connect to app from IDE while all of my services landscape is running. 

Currently Kurtosis maps it to random number. In vanilla docker I can map `-p 40000:40000`. How to do such map with [service config](https://docs.kurtosis.com/starlark-reference/service-config)?

### Desired behaviour

[`PortSpec`](https://docs.kurtosis.com/starlark-reference/port-spec) has a settable parameter public mapping target. Start-Run fails if port already taken.

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by leeederek** [comment]
Hey @OlegJakushkin, this is not currently supported but your feedback is helpful for us to prioritize this in coming releases. Kurtosis enclaves can be left running for as long as you need it to be online for.

Can you elaborate further on what your workflow is & why you need to start from a brand new enclave each time? We have [idempotent runs](https://docs.kurtosis.com/explanations/how-do-idempotent-runs-work) enabled by default, meaning that on each run (against the same enclave), Kurtosis will only apply the difference to the enclave between each run. I'm wondering if this is something that would help you? 

In either case, thank you filing this issue - looking forward to hearing back and to see how we can help :)

**Comment by OlegJakushkin** [comment]
Dear @leeederek: l looked into your sources and found [undocumented](https://docs.kurtosis.com/starlark-reference/service-config) Service [`public_ports`](https://github.com/kurtosis-tech/kurtosis/blob/main/container-engine-lib/lib/backend_interface/objects/service/service_config.go#L22) API, and [here is example](https://github.com/kurtosis-tech/near-package/blob/5923d58c79633134823875c8dd95d355a3b82a05/src/services/indexer.star#L69-L70) of its use by kurtosis-tech.

So probably feature is implemented already, yet a little bit hard to find. Please document it.

**Comment by h4ck3rk3y** [comment]
Hey @OlegJakushkin - That is undocumented as we consider it a hack for a feature that we want to properly implement but this hack has been around for over an year now. We had added this to support the `near-package` use case but haven't replaced it with something proper yet!

![image](https://github.com/kurtosis-tech/kurtosis/assets/6670312/f8880bb3-f445-44e4-8462-c59842ab0c31)

This meme comes to mind. Having said that; we have heard this often enough for it to be on the top of our queue! I think we also have an engineer assigned to it for mid Oct/November; will ping you when its out.

**Comment by OlegJakushkin** [comment]
@h4ck3rk3y: As it is public, already known API that you use for a [year](https://github.com/kurtosis-tech/near-package/commit/40c22cb04f7eaf983b20d3d5f798a3662c9cee8e) in a public OSS project I would definitely consider it known feature not subject to big change from a user standpoint=) And user facing part (API) is not really bound with how you would change its implementation. 

So we will use it as you do in Near. And when you will make any change will have info on how to do update our code looking at Near. 
Thank you.
