### ISSUE TITLE
Provide visual indication in frontend when the Starlark script succeeds/errors

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1480]
### Background & motivation

Right now, it's unclear when the Starlark script is done, or a step is just taking a while.

### Desired behaviour

When the Starlark script succeeds, I get a green indicator indicating that the Starlark is done. If it fails, I get a red indicator showing that it errored.

A nice design might be, having a thing under the log display with three states:
- Running...
- Succeeded
- Failed

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
Even better idea: show the progress bar

**Comment by adschwartz** [comment]
Done
