### ISSUE TITLE
docs: Add type information to return value of read_file reference

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis#1483]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/starlark-reference/read-file/

### Issue description

It's not clear what read_file returns to me, so I don't know how to plug it in to other starlark functions

**Comment by leeederek** [comment]
Thanks @galenmarchetti! The contents of the file are returned as a string! I'll make sure to add docs for this.
