### ISSUE TITLE
docs: Kurtosis config file format isn't documented

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1488]
### Where did you see the issue in our documentation?

docs.kurtosis.com

### Issue description

We don't have docs for the Kurtosis CLI config file format. It's becoming an increasingly important part of Kurtosis (proxy, Docker socket, etc.), and the docs should have the complete specification.

**Comment by mieubrisse** [comment]
Data: this has been repeatedly painful; would be very nice to have

**Comment by h4ck3rk3y** [comment]
Now available on 

https://docs.kurtosis.com/k8s/#iii-add-your-cluster-information-to-kurtosis-configyml
https://docs.kurtosis.com/cluster-set/
