### ISSUE TITLE
FR: make it more obvious that package names in the package catalog are case sensitive

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#1494]
### Background & motivation

The Kurtosis package catalog search bar is case sensitive - I didn't know this and so when I was trying to deploy a the hyperlane package, I couldn't find the package when I used `Hyperlane` and could only find it when I typed `hyperlane` in the search bar.

<img width="1984" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/1fbd4772-a4e0-4683-a036-1cde33ec150c">

<img width="1979" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/b5f10748-deb7-45b1-bd59-bb4251ed9d50">

### Desired behaviour

To me, this is annoying because I did not expect the package catalog to be case sensitive. The ask here is to either:
1. Remove the case sensitivity restriction OR
2. Add a tool tip/disclaimer/banner to tell a user that its case sensitive

I prefer (1)

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
IMO we should remove the case-sensitivity restriction

**Comment by mieubrisse** [comment]
No longer the case
