### ISSUE TITLE
In cluster ls have an * next to the currently chosen cluster

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1508]
### Background & motivation

This would match context ls

### Desired behaviour

kurtosis cluster ls

looks like

* docker
kubernetes
minikube

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by galenmarchetti** [comment]
Would also be great to match the verbs in Kurtosis context and Kurtosis cluster ... right now one uses switch and the other uses set, and I keep mixing them up

**Comment by omar711** [comment]
Small issue, on a new environment, the cluster-settings file doesn't exist yet, so `kurtosis cluster get` will fail:

```
√ kurtosis % kurtosis cluster get
Error:  An error occurred running command 'get'
  Caused by: Failed to get cluster setting.
  Caused by: Failed to get cluster setting from setting file.
  Caused by: An error occurred reading cluster setting file
  Caused by: open ~/Library/Application Support/kurtosis/cluster-setting: no such file or directory
```

**Comment by omar711** [comment]
@galenmarchetti  @h4ck3rk3y I've updated this to match context, and also used the table_printer used there to match.  Currently it looks like this:

```
√ kurtosis % ./cli/cli/scripts/launch-cli.sh cluster ls
    Name
*   docker
    minikube
```

The column header is new, due to the table printer.  Is that ok or do you prefer the plain version?

**Comment by omar711** [comment]
> Would also be great to match the verbs in Kurtosis context and Kurtosis cluster ... right now one uses switch and the other uses set, and I keep mixing them up

on this @galenmarchetti : do you prefer set or switch?  Any concerns around changing one (e.g. in cases users have scripted it)?

**Comment by galenmarchetti** [comment]
great! I remember @mieubrisse had a strong opinion about this one, maybe @h4ck3rk3y  remembers this...one of these verbs represents idempotent changes so both should be whichever that verb is. i'm butchering it. @mieubrisse  thoughts?

**Comment by galenmarchetti** [comment]
confirmed with @mieubrisse  it should be `set` because its a natural pairing with `get` and also implies idempotency

**Comment by omar711** [comment]
`cluster ls` is done now https://github.com/kurtosis-tech/kurtosis/pull/1514 
I'll keep this open and tackle the `context switch/set` part in a separate pr tomorrow

**Comment by omar711** [comment]
All done - noting https://github.com/kurtosis-tech/kurtosis/issues/1536 which will eventually drop the `context` command in favour of a `cloud` one
