### ISSUE TITLE
frontend sends parallelism of 0 which breaks add_services

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1511]
### What's your CLI version?

0.84.3

### Description & steps to reproduce

Try running github.com/galenmarchetti/basic-service-package from the cloud or web ui and you will see it gets stuck as it uses `add_services`

Do docker logs on the core and you will see parallelism is passed as 0

https://github.com/kurtosis-tech/kurtosis/commit/4af67d5d12af30919afcdf8701432ab6ee92a4ca

this is a stop gap that should be reverted ^

### Desired behavior

Parallelism 4 should be passed by frontend to backend by default. CLI should stream logs; core logs should be visible on Cloud

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Frontend

**Comment by mieubrisse** [comment]
Believe this is now fixed
