### ISSUE TITLE
Auto format JSON objects in package configuration screen

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/kurtosis#1515]
### What's your CLI version?

0.84.3

### Description & steps to reproduce

When pasting a json into a json package arg in the package configuration screen, I have to click the format button to format it.

### Desired behavior

The json is formatted automatically.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
I like this

**Comment by mieubrisse** [comment]
Done now
