### ISSUE TITLE
Allow to mount multiple artifacts to the same folder in a service

### ISSUE THREAD

**Issue by cbermudez97** [kurtosis-tech/kurtosis#1519]
### Background & motivation

When creating a new service it is not possible to add multiple artifacts to the same path in the `files` dictionary. For example, in this code there is no direct way to put both files inside the `/files` directory in the service:

```python
def run(plan, args={}):
    artifact_name_1 = plan.upload_files("./folder-1/file-1.txt")
    artifact_name_2 = plan.upload_files("./folder-2/file-2.txt")

    service = plan.add_service(
        "service-example",
        config=ServiceConfig(
            image="alpine:latest",
            command=["ls", "/files"],
            files={
                "/files": artifact_name_1,
                # "/files": artifact_name_2,
            },
        ),
    )
```

**Workaround:**

Currently, this is possible with the use of [plan.run_sh](https://docs.kurtosis.com/starlark-reference/plan#run_sh), mounting artifacts to different directories, combining them with the shell command(`cp`, `mv`, or similar), and later extracting a new artifact using the `store` parameter. This new artifact can be mounted in the others services.

### Desired behaviour

It should be possible to allow the use of the same path for multiple artifacts that aren't loaded together. Also, allowing to combine artifacts in an easier way could also solve this issue.

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by h4ck3rk3y** [comment]
Relevant - https://github.com/kurtosis-tech/kurtosis/issues/378
