### ISSUE TITLE
Change "Why we built Kurtosis" to "Why Kurtosis?"

### ISSUE THREAD

**Issue by chunha-park** [kurtosis-tech/kurtosis#1565]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/explanations/why-we-built-kurtosis/

### Issue description

Per Will from OP, change "Why we built Kurtosis" to "Why Kurtosis" to better reflect reader priorities.

**Comment by itsayopapi** [comment]
@chunha-park can i work on this issue?

**Comment by leeederek** [comment]
Hey @itsayopapi - yes you may :)
