### ISSUE TITLE
Discord invite link invalid

### ISSUE THREAD

**Issue by Dartoxian** [kurtosis-tech/kurtosis#1575]
### Where did you see the issue in our documentation?

https://github.com/kurtosis-tech/kurtosis/blob/main/README.md

### Issue description

The discord invite link in the primary README and issue template is not working
* https://github.com/kurtosis-tech/kurtosis/blob/main/.github/ISSUE_TEMPLATE/config.yml
* https://github.com/kurtosis-tech/kurtosis/blob/main/README.md
* https://github.com/kurtosis-tech/kurtosis/blob/main/CONTRIBUTING.md

The following screen is seen:

![image](https://github.com/kurtosis-tech/kurtosis/assets/4419574/c747c479-b386-4904-a9e0-f0cbca7fd5ac)

**Comment by leeederek** [comment]
Thank you @Dartoxian - super helpful. Will update!
