### ISSUE TITLE
CLI should default to showing help when zero args are provided

### ISSUE THREAD

**Issue by omar711** [kurtosis-tech/kurtosis#1576]
### Background & motivation

When you're exploring the cli, you often run into a relatively unhelpful error:

```
% kurtosis service shell
Error:  accepts between 2 and 2 arg(s), received 0
```

You then run it again with the `-h` flag to see what it wants from you.

### Desired behaviour

If the command expects args that aren't given, show the relevant help, i.e.:

```
% kurtosis service shell
Starts a shell on the specified service

Usage:
  kurtosis service shell [flags] enclave service

Flags:
  -h, --help   help for shell

Global Flags:
      --cli-log-level string   Sets the level that the CLI will log at (panic|fatal|error|warning|info|debug|trace) (default "info")
```
(maybe include the error note too)

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by mieubrisse** [comment]
Re. the "show help when no args are provided" - Galen hit a pain point with this where _some_ commands do this (e.g. `kurtosis`, `kurtosis enclave`) but not all (e.g. `kurtosis service shell`). I'm actually wary of simply enabling "no args == help", because it encourages people to just run the command, and it might actually accept no arguments and do something they don't expect. I'd prefer that we disable _all_ instances of "no args == help", in favor of explicit "pass `-h` to see help".

That said, I think the spirit of this ticket is actually subtly different: when the user doesn't provide the right number of args, we should throw an error (like we need to) but ALSO show the possible args. This I agree with; it's a convenience in case you mess up the arguments rather than "the default for checking helptext is pass no args".

**Comment by leeederek** [comment]
@omar711, adding to what Kevin mentioned above: what do you think of the below behavior?

```
% kurtosis service shell
Error:  this command requires 2 arguments: the $ENCLAVE_IDENTIFIER 
followed by the $SERVICE_NAME. Read more about this command [here](link-to-docs)
```

**Comment by omar711** [comment]
@leeederek yeah that would be cool, although I don't think we need to interpret user input too much.  Simply noting they've not given the correct args and showing some help on usage, would be plenty.  

Examples:

```
% mv 1
usage: mv [-f | -i | -n] [-hv] source target
       mv [-f | -i | -n] [-v] source ... directory
```

Or docker, which shows a succint usage in case of missing args, and a full usage when `--help` is passed in:

```
?1 kurtosis-portal % docker exec
"docker exec" requires at least 2 arguments.
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Execute a command in a running container
?1 kurtosis-portal % docker exec --help

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Execute a command in a running container

Aliases:
  docker container exec, docker exec

Options:
  -d, --detach               Detached mode: run command in the background
      --detach-keys string   Override the key sequence for detaching a container
  -e, --env list             Set environment variables
      --env-file list        Read in a file of environment variables
  -i, --interactive          Keep STDIN open even if not attached
      --privileged           Give extended privileges to the command
  -t, --tty                  Allocate a pseudo-TTY
  -u, --user string          Username or UID (format: "<name|uid>[:<group|gid>]")
  -w, --workdir string       Working directory inside the container
```

**Comment by mieubrisse** [comment]
I just hit this again personally with:
```
$ kurtosis package init
Error:  accepts between 1 and 1 arg(s), received 0
```

**Comment by mieubrisse** [comment]
Found out that this is coming from Cobra itself, the library we use for command-line args: https://github.com/spf13/cobra/blob/5c962a221e70fd6b12296e5d7075f28b422f98b2/args.go#L107

**Comment by mieubrisse** [comment]
The work for this ticket is probably to:
- Disable Cobra's vague args-handling
- Use our own args-handling, and probably print the helptext when missing a required arg

**Comment by omar711** [comment]
There's a PR at https://github.com/kurtosis-tech/kurtosis/pull/369/files#diff-df91c4aa5f0e159b2964285857f6b5378b210ebef569c10451a54bd843a50e7eL87 which sets `SilenceUsage`, that may be related.  Looks like we did it to supress excess usage though so might need to find the right sweet spot.  Here's the cobra flag too https://github.com/spf13/cobra/blob/5c962a221e70fd6b12296e5d7075f28b422f98b2/command.go#L231
