### ISSUE TITLE
typo in code

### ISSUE THREAD

**Issue by franjoespejo** [kurtosis-tech/kurtosis#1591]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/quickstart/#spin-up-your-system

### Issue description

Replace 

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file ~/network_params.json --enclave eth-network"`

With

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file ~/network_params.json --enclave eth-network`

**Comment by omar711** [comment]
Thanks for flagging!  Fix is waiting in https://github.com/kurtosis-tech/kurtosis/pull/1593
