### ISSUE TITLE
Allow kurtosis run to take a json file from url

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1596]
### Background & motivation

Currently the args-file can take a local image only. 

```sh
kurtosis run github.com/kurtosis-tech/ethereum-package --args-file https://raw.githubusercontent.com/ethpandaops/dencun-testnet/bbusa/devnet-10/kurtosis/devnet-10.json
Error:  An error occurred running command 'run'
  Caused by: An error occurred calling the run function for command 'run'
  Caused by: attempted to read file provided by flag 'args-file' with path 'https://raw.githubusercontent.com/ethpandaops/dencun-testnet/bbusa/devnet-10/kurtosis/devnet-10.json' but failed
  Caused by: open https://raw.githubusercontent.com/ethpandaops/dencun-testnet/bbusa/devnet-10/kurtosis/devnet-10.json: no such file or directory
```

### Desired behaviour

It would be great if it could take a remote file also.

For example it would be great if this would be supported: 

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file https://raw.githubusercontent.com/ethpandaops/dencun-testnet/bbusa/devnet-10/kurtosis/devnet-10.json`

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by leeederek** [comment]
Thanks @barnabasbusa for filing this. 

To recap the behavior you'd expect (we chatted over discord, but putting this here for everyone else)
- If the link contains an invalid `json`, return an error that looks like:
```
> Error:  An error occurred validating arg 'args'
>   Caused by: Error validating args, because it is not a valid JSON or YAML.
>   Caused by: JSON parsing error 'invalid character 'f' after object key', YAML parsing error 'yaml: did not find expected ',' or '}''

```
- If its a dead link, return a 404
