### ISSUE TITLE
Enable setting the user that the container runs with

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis#1632]
### Background & motivation

I want to set the user that a container runs with, like the --user command to the `docker` command line. My image has functionality that can only be unlocked by modifying the user who runs the container

### Desired behaviour

Ability to set the user that runs the container

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

SDK: the Software Development Kit libraries - Typescript, Go, etc.

**Comment by mieubrisse** [comment]
Now done via https://docs.kurtosis.com/api-reference/starlark-reference/user/
