### ISSUE TITLE
Add missing flags to `kurtosis run --help`

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1651]
### Where did you see the issue in our documentation?

`kurtosis run --help`

### Issue description

When you run kurtosis run --help, you should see all the possible parameters that you can pass.

A few missing features that I have failed to see are: 
*`--args-file` flag now takes a URL. 
* `--always-pull` flag is missing.
* I'm sure there are some other flags that are now implemented but are missing from the `--help` window.

**Comment by leeederek** [comment]
Hey @barnabasbusa - what version of the CLI are you on? I see both of the flags when I run `kurtosis run --help`:
```bash
Flags:
      --args-file string            The file (JSON/YAML) will be used as arguments passed to the Kurtosis Package
      --image-download missing      If unset, it defaults to missing for fetching the latest image only if not available in local cache. Use `always` to always fetch the latest image. (default "missing")
```

I believe you are on an older version of the CLI so thats why you might not see it!

**Comment by leeederek** [comment]
Closing this out as completed! Just make sure you're on the latest and greatest Kurtosis :)
