### ISSUE TITLE
Kurtosis cloud - Configure selectable favorites for enclave packages

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1653]
### Background & motivation

It would be great to be able to highlight a few catalog elements as favorites, and would list only those, prioritize them over others.

![Screenshot 2023-10-30 at 16 31 40](https://github.com/kurtosis-tech/kurtosis/assets/21987084/80fc73c7-8a52-4245-bfa5-50a28b1b92d0)

### Desired behaviour

-

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

### What area of the product does this pertain to?

SDK: the Software Development Kit libraries - Typescript, Go, etc.

**Comment by mieubrisse** [comment]
Closing in favor of #1786
