### ISSUE TITLE
[Docs]: Kurtosis upgrade docs should have `brew update && ` before it

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#167]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/install

### Description of the issue

Due to the way that brew works, you can get into a situation where a new Kurtosis version is released and you're getting the annoying warning, but `brew upgrade kurtosis-cli` says that you're on latest. The upgrade docs for Mac should be `brew update && brew upgrade kurtosis-cli`

**Comment by leeederek** [comment]
Looks like this is taken care of by #208. Will close this out once #208 is merged.

**Comment by leeederek** [comment]
#208 is now merged, closing this issue out.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/103802618/225674767-39063422-42d4-4038-ba26-0bd93e202386.png">
