### ISSUE TITLE
[Docs]: `kurtosis feedback` doesn't have info on the various flags, the message arg, and how they interact

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#168]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/feedback

### Description of the issue

Not in the docs, so it doesn't exist!

More detailed information on the pain i'm hitting: https://kurtosistech.slack.com/archives/C04N80JM44V/p1678805078067509?thread_ts=1678413095.469739&cid=C04N80JM44V

**Comment by leeederek** [comment]
Hey @mieubrisse , I've opened #231 if you wanted to take a look at that! Let me know what you think!
