### ISSUE TITLE
add a built by Kurtosis banner to the output of Kurtosis run

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1680]
### Background & motivation

This is to prevent wrappers from hiding whats running inside

### Desired behaviour

We should print a `Made by Kurtosis` with a link at the end of the run

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by mieubrisse** [comment]
Datapoint: we should probably send this in the stream coming back from the APIC (rather than building this in the CLI)

**Comment by h4ck3rk3y** [comment]
Added this in #1687
