### ISSUE TITLE
[Docs]: Remove deprecation warnings for old recipes

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#172]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/reference/starlark-types/#execrecipe

### Description of the issue

On both https://docs.kurtosis.com/reference/starlark-types/#execrecipe and https://docs.kurtosis.com/reference/starlark-instructions#wait , there are loud warnings about recipe stuff that I believe was deprecated last year. We can probably just do the break now, and remove the warnings. Adding @victorcolombo because he knows most about this

**Comment by leeederek** [comment]
Removing Victor and adding Leandro. @leoporoli is tracking to remove this during the *next* breaking change release scheduled for the week of March 20, 2023. Will close this Issue when that change is in.

**Comment by leeederek** [comment]
Branch in question: https://github.com/kurtosis-tech/kurtosis/tree/2023-03-22-breaking-release
