### ISSUE TITLE
run_sh tasks are being reported as services when they are not

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/kurtosis#1736]
### What's your CLI version?

0.85.9

### Description & steps to reproduce

`kurtosis run github.com/kurtosis-tech/ethereum-package`

<img width="858" alt="Screen Shot 2023-11-09 at 4 51 14 PM" src="https://github.com/kurtosis-tech/kurtosis/assets/46531991/a98fb4b6-cbc8-4e57-9bec-cc5b5b885427">

### Desired behavior

Tasks from `run_sh` or `run_python` are not listed as user services.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by mieubrisse** [comment]
Proper fix here is to add a new `Tasks` section in the enclave output

**Comment by h4ck3rk3y** [comment]
Closed with #1683
