### ISSUE TITLE
"Execution in progress" hangs for 10 minutes and then "Error encountered running Starlark code."

### ISSUE THREAD

**Issue by thib-wien** [kurtosis-tech/kurtosis#1769]
### What's your CLI version?

0.85.18

### Description & steps to reproduce

My environment with Kurtosis was working last week. I restarted the computer and now I face the following problem.

When starting Kurtosis, the screen freezes with this for 10 minutes:
![Screenshot from 2023-11-13 10-25-58](https://github.com/kurtosis-tech/kurtosis/assets/150015231/81e1e1a4-245e-4083-af71-89b64316456d)

After having been frozen for 10 minutes, Kurtosis throws this error:
![Screenshot from 2023-11-12 18-12-40](https://github.com/kurtosis-tech/kurtosis/assets/150015231/cb8f3526-a8e8-4dd1-add8-8653e6bb90d7)

The problem might be between the screen and the chair.

### Desired behavior

An error message sooner maybe.
But I am not sure what the origin of the problem is: me, the scripts or Kurtosis?

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by mieubrisse** [comment]
Hey @thib-wien , thanks for filing this and apologies in the response delay (the team is at a conference, so we're going to be slower than usual to respond this week)! This does indeed look like a problem with Kurtosis; the specific error that's happening is that Kurtosis is checking to see if our centralized logs collector is available before starting the service, and it's failing. 

Would you mind running a `kurtosis enclave dump my-testnet` and sending the output directory to us? That will contain logs on the enclave, so we can see what's going on. You can send it to support@kurtosistech.com if it contains sensitive data that you're not comfortable posting on this issue.

**Comment by thib-wien** [comment]
Thanks a lot for considering the problem.
I sent you data by email.

**Comment by tedim52** [comment]
Hey @thib-wien thank you for sending, taking a look at the data now! Also, just wanted to confirm, is this issue happening when you try and run any kurtosis package or were you seeing this issue only when running this specific package?

**Comment by thib-wien** [comment]
Thanks!
I haven't tried with another package. I am given only this one at my workplace.

**Comment by thib-wien** [comment]
PS: you write "_were you seeing this issue_" but I am still seeing it. I tried various things and nothing fixes the problem unfortunately.

**Comment by tedim52** [comment]
Gotcha! It seems like you're trying to run the full beacon node in the ethereum package. Any chance you can send the network params yaml so I can try and reproduce on 0.85.18?

**Comment by thib-wien** [comment]
Gladly!
Do you find [in this folder](https://github.com/gobitfly/eth2-beaconchain-explorer/tree/master/local-deployment) the parameters that you need to see?

**Comment by tedim52** [comment]
yes! Thanks you.

**Comment by thib-wien** [comment]
Dear Kurtosis team,

We fixed our problem this morning by uninstalling Docker, deleting all data that it left on my computer and reinstalling it.

We suspect that `sudo docker system prune --volumes -a -f` would be sufficient (it might avoid the removal of dozens of folders by hand). If someone encounters my problem one day, try this command.

We hope that you will figure out the problem that I experienced with your log collector. We keep an eye on this page and are ready to help you at our level.

**Comment by tedim52** [comment]
Hey @thib-wien ! Thanks for getting back to us and letting us know how you solved the issue and apologies for the late reply (our team is returning from a long week at a conference) We believe we may have some resource leakage around our log collector containers and your problem/solution may back that hypothesis. We're tracking this issue here: https://github.com/kurtosis-tech/kurtosis/issues/1833 so I'll close out this issue for now. If you have any more info regarding this one your end, don't hesitate to reach us there. Thanks again for your support!
