### ISSUE TITLE
FR[cloud]: Enable YAML configuration on kurtosis cloud

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1785]
### Background & motivation

Currently, kurtosis cloud doesn't take yaml as a configuration parameter.

### Desired behaviour

Accept YAML. 

<img width="1030" alt="Screenshot 2023-11-15 at 02 02 20" src="https://github.com/kurtosis-tech/kurtosis/assets/21987084/55a76fc7-3f4c-4056-b397-843de66c1656">

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
Hey @barnabasbusa , this should be available now! Can you give it a test and let me know?

**Comment by mieubrisse** [comment]
Closing, as this is now available
