### ISSUE TITLE
Cloud: Can't scroll if there is an error in the enclave name

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1787]
### What's your CLI version?

N/A

### Description & steps to reproduce

If you have an error in the enclave creation, it will throw a kurtosis error, but the error itself if not scrollable, which makes it difficult to debug/understand what caused the issue.

<img width="1050" alt="Screenshot 2023-11-15 at 02 10 31" src="https://github.com/kurtosis-tech/kurtosis/assets/21987084/7b0ddc39-ae46-46c0-9815-d10412276cb5">

Steps to reproduce:

Create an enclave, call it : A
Create another enclave, also call it: A

It will have an issue due to conflicting name, and then expand the error message, and try to close it/scroll it. 

### Desired behavior

Being able to scroll or at least close the error message. 

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
Repro'd on Chrome:
<img width="1496" alt="Screen Shot 2023-11-15 at 13 58 16" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/ff08e8b5-0403-4bb6-b302-0fe052fc40fd">

<img width="1496" alt="Screen Shot 2023-11-15 at 13 58 12" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/9cd9b4fc-6e83-4d68-81bb-893f99c68c69">

**Comment by adschwartz** [comment]
I think this is in @Dartoxian's wheel house. Ben let me know if you disagree. Added to burndown as well
