### ISSUE TITLE
Cloud: custom configuration doesn't spin up required config

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1789]
### What's your CLI version?

N/A

### Description & steps to reproduce

When I specify a custom config on kurtosis cloud, I still seem to get the default config. 

e.g: I have used this config:
```json
{
  "participants": [
    {
      "el_client_type": "geth",
      "cl_client_type": "lighthouse"
    },
    {
      "el_client_type": "besu",
      "cl_client_type": "prysm"
    }
  ],
  "network_params": {
    "deneb_fork_epoch": 1,
    "seconds_per_slot": 9
  },
  "additional_services": [
    "el_forkmon",
    "dora",
    "prometheus_grafana"
  ],
  "mev_type": null
}
```

See screenshot below:

<img width="1344" alt="Screenshot 2023-11-15 at 02 17 46" src="https://github.com/kurtosis-tech/kurtosis/assets/21987084/4dc1fa0b-4ddc-4268-8cf7-693910c2d9d5">
<img width="1056" alt="Screenshot 2023-11-15 at 02 17 39" src="https://github.com/kurtosis-tech/kurtosis/assets/21987084/eb056084-1fcb-4a07-80a6-173699d67578">

uuid: 66a897a354f1

### Desired behavior

I should see
 
participants:
  - el_client_type: geth
    cl_client_type: lighthouse
  - el_client_type: besu
    cl_client_type: prysm

(Also I should be able to use yaml, but thats another issue already https://github.com/kurtosis-tech/kurtosis/issues/1785)

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
Oo thanks for filing @barnabasbusa ; that's definitely a bug! @adschwartz can you take a look at this?

**Comment by adschwartz** [comment]
@barnabasbusa Thanks so much for filing this issue. I've submitted a PR that fixes your problem. 

Running the `ethereum-package` with the standard (no) args yields these (relevant) services:

![image](https://github.com/kurtosis-tech/kurtosis/assets/11248996/3c580115-c3d5-43c0-883a-c3960b1080f0)

Running the `ethereum-package` with the args you provided above yields these (relevant) services:

![image](https://github.com/kurtosis-tech/kurtosis/assets/11248996/8c470010-366c-4604-8746-436cb12cc5b4)

Hopefully this solves your problem. If not, please reach out again. Thanks!
