### ISSUE TITLE
Cloud: unable to find all occurrences of searched item in logs

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1791]
### What's your CLI version?

N/A

### Description & steps to reproduce

When I try to find a certain log entry in https://cloud.kurtosis.com/enclave-manager/enclave/66a897a354f1/service/151acad62d58/logs I can't seem to find all occurrences of searched object with cmd+f. 

### Desired behavior

Would be good to either include a search box in the logs tab, or enable me to search the whole logs file with cmd+f. 

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
Hey @barnabasbusa thanks for filing! The way the frontend currently works is that it loads the first couple thousand (I believe it's 2k) loglines and then cmd-f will operate on that. Is the logline you're looking for from beyond the first 2k lines? Or, is the bug related to a match that you're seeing in the frontend not getting matched?

**Comment by mieubrisse** [comment]
Repro'd with Barnabas - the search terms that are loaded in the frontend, but not immediately visible, _aren't_ getting matched:

<img width="1488" alt="Screen Shot 2023-11-15 at 13 52 45" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/61485e9b-fb45-4eb8-8d16-fdfa45d3a7a2">

**Comment by adschwartz** [comment]
it appears that when you search it only highlights what's in the viewable port. Seems to be a limitation with react-virtuoso? virtuoso doesn't seem to have any native search capabilities. @Dartoxian may be we'll need a custom search function?

**Comment by Dartoxian** [comment]
yep I think you're right @adschwartz . I think it would be reasonable to intercept ctrl+f and provide search capability in the log view, then control scrolling react-virtuoso ourselves to navigate results..
