### ISSUE TITLE
[Docs]: It's unclear what the `extract` field is of the XXXHttpRequest objects from the comment above them

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#186]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/reference/starlark-types/#httprequestrecipe

### Description of the issue

The current comment on `extract` is:
```
            # The extract dictionary takes in key-value pairs where:
            # Key is a way you refer to the extraction later on
            # Value is a 'jq' string that contains logic to extract from response body
            # # To lean more about jq, please visit https://devdocs.io/jq/
```
This defines _what_ it is, but not how it's useful. Something better would be explaining what an extract is, and how you'd use it.

RELEVANCE: I wasn't actually sure if I needed an `extract` or not

**Comment by leeederek** [comment]
Hey @mieubrisse, I've opened #235 to address this. Let me know your thoughts on that implementation!
