### ISSUE TITLE
Support logo in starlark markup

### ISSUE THREAD

**Issue by Dartoxian** [kurtosis-tech/kurtosis#1872]
### Background & motivation

Our designs allow for a custom package logo in the catalog cards 
![image](https://github.com/kurtosis-tech/kurtosis/assets/4419574/cd7931ad-8a84-4ae7-bae8-65ea8d12c86d)

### Desired behaviour

Please could support for a logo (as a public url?) be added to the package definition and returned in the package indexer.

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mud1tx** [comment]
@Dartoxian I can work on this but can you explain a little more.

**Comment by Dartoxian** [comment]
Hi @mud1tx - the screenshot above is a mockup of how the enclave manager ui catalog view should look. In it each package is able to have its own custom logo, and if it's not present then we just use a kurtosis logo.

The logo presumably should be defined in the starlark markup so that https://github.com/kurtosis-tech/kurtosis-package-indexer is able to return the logo as a full url in its `KurtosisPackage` object (presumably `kurtosis-package-indexer` needs to be updated as well).

**Comment by leoporoli** [comment]
@mud1tx This is a backend task on this repository https://github.com/kurtosis-tech/kurtosis-package-indexer 
it's a Golang GRPC server that contains two endpoints returning the [kurtosis package](https://github.com/kurtosis-tech/kurtosis-package-indexer/blob/main/api/protobuf/kurtosis_package_indexer.proto#L32) basically what you have to do is add a new field on this type which will return the "Kurtosis Package Icon" image URL, so the FE can get this URL and download the image.

The BE should check if the image exist in the expected repo path (it should be next to the kurtosis.yml file, in the same folder and the name should be `kurtosis-package-icon.png`) if the image doesn't exist it could return the GitHub org image instead and if it's empty, it should return an empty string.

@mud1tx let me know if you need more details

**Comment by leoporoli** [comment]
it was implemented here: https://github.com/kurtosis-tech/kurtosis-package-indexer/pull/70 and here: https://github.com/kurtosis-tech/kurtosis-package-indexer/pull/72
