### ISSUE TITLE
[Docs]: PostHttpRequestRecipe and GetHttpRequestRecipe should have their own sections in the Starlark Types docs

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#189]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/reference/starlark-types

### Description of the issue

The right navigation index's theme is "one header per type". I'm using a `PostHttpRequestRecipe`, but it doesn't exist - it's instead buried under an `HttpRequestRecipe` meta-header. We should standardize this

**Comment by leeederek** [comment]
Hey @mieubrisse, I've opened: https://github.com/kurtosis-tech/kurtosis/pull/251 to address this. Let me know what you think!
