### ISSUE TITLE
[Docs]: multiple typos in HttpRequestRecipe callout

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#190]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/reference/starlark-types/#httprequestrecipe:~:text=Important%20%2D%20port_id%20field%20accepts

### Description of the issue

"assinged"
"defininig"
non-propercase "http" in "create http request recipes"
Missing several articles like "the" throughout the text, e.g. "The user defined port IDs in above port map"

**Comment by leeederek** [comment]
I've opened the above to address this! Let me know what you think!
