### ISSUE TITLE
Add logs to cli

### ISSUE THREAD

**Issue by igor-ritual** [kurtosis-tech/kurtosis#1903]
### Background & motivation

Currently to follow service logs I perform:
```
docker ps | grep [service name]
docker logs -f [service pid]
```

### Desired behaviour

It would be great to do this instead:
```
kurtosis logs -f [service name]
```

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by tedim52** [comment]
Hey @igor-ritual - have you checked out`kurtosis service logs <enclave name> <service name> -f`? Let me know if that works for ya! Here's the docs: https://docs.kurtosis.com/service-logs

**Comment by igor-ritual** [comment]
Perfect!
