### ISSUE TITLE
support persistent volumes in kubernetes over multiple nodes

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1904]
### Background & motivation

We support persistent directories in Docker and a single nodes k8s cluster ;we want it for multi node clusters enabling EF, others and persistent logs in k8s

### Desired behaviour

Persistent Directories work in multinode k8s clusters

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by jimmygchen** [comment]
Hi @h4ck3rk3y, has this feature been implemented?
