### ISSUE TITLE
[FR]: `wait` should default to `code` `==` (`0` for exec, `200` for requests)

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#191]
### Background and motivation

There's a bunch of information that's work to specify with a `wait`, and requires me knowing what the `wait` fields are and how they work. I'd have expected I just toss in a recipe and Kurtosis figures it out.

### Current behavior

I have to specify the assertion, the comparison, and the value.

### Desired behavior

Kurtosis defaults to `code` `==`, and uses `0` for execs and `200` for requests.

Docs are, of course, updated to reflect this

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by h4ck3rk3y** [comment]
@victorcolombo is this done now?

**Comment by victorcolombo** [comment]
Closed by https://github.com/kurtosis-tech/kurtosis/pull/212
