### ISSUE TITLE
[FR]: all TCP ports for a service should automatically get a wait that checks if they're open

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#192]
### Background and motivation

When building the quickstart, I found it to be quite cumbersome to build the various recipes (particularly HTTP). I realized that I'm already telling Kurtosis the ports, and if Kurtosis can do a simple "don't proceed until all ports are open" check then we'd solve a LOT of user pain.

### Current behavior

User has to manually wire up the waits in a bunch of different ways, and can ONLY do HTTP requests (which require a ton of information to configure).

### Desired behavior

By default, all TCP ports that get defined on a service come with a simple TCP-level "can Kurtosis connect to the port?" wait.

The user can also add extra configuration to define:
- Turning off the wait entirely
- Timeouts
- Initial delay

### How important is this feature or improvement to you?

Painful, the lack of this feature makes using Kurtosis frictionful.

**Comment by leoporoli** [comment]
The first PR got merged, but the feature is not active yet.
