### ISSUE TITLE
find a better way to overwrite previous releases on brew

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1937]
### What's your CLI version?

0.85.44

### Description & steps to reproduce

We had a bug where we published a wrong / broken version of the CLI

brew was installing a broken release while 0.85.42 was the working one

### Desired behavior

i want to overwrite an existing release with a simple command

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by mieubrisse** [comment]
@h4ck3rk3y overwriting release history seems odd to me; release history seems like it gets much easier if it's append-only (just release a new version if something is broken). Do you still want to keep this ticket open?

**Comment by h4ck3rk3y** [comment]
Fair enough Kevin; yeah release should be append only and if that is slow that slowness should be killed.
