### ISSUE TITLE
[Docs]: Get/PostHttpRequestRecipe docs on "Starlark Types" don't explain the `extract` field at all

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#194]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/reference/starlark-types#httprequestrecipe

### Description of the issue

These docs are instead on the `request` section of Starlark instructions. I believe this to be backwards. Once we do this and #193 I think this should be cleaned up.

**Comment by leeederek** [comment]
I've opened: https://github.com/kurtosis-tech/kurtosis/pull/235 to address this
