### ISSUE TITLE
Two documentation sections with the same name 'Advanced Concepts > Idempotent Runs'

### ISSUE THREAD

**Issue by avorobyov** [kurtosis-tech/kurtosis#1960]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/advanced-concepts/idempotent-runs

### Issue description

<img width="250" alt="Screenshot 2023-12-14 at 12 10 14 PM" src="https://github.com/kurtosis-tech/kurtosis/assets/248884/e3f6d93d-4759-45c9-8c25-025ffe39c87c">

**Comment by leeederek** [comment]
Hey @avorobyov! Thank you for highlighting this! Our docs are currently undergoing a revamp and we will most definitely fix this part of our documentation.
