### ISSUE TITLE
Use synthetic monitor for static URL testing

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/kurtosis#1968]
### What's your CLI version?

0.85.46

### Description & steps to reproduce

Right now, several links report 400 unexpected error even if the links work eg. 
![image](https://github.com/kurtosis-tech/kurtosis/assets/46531991/ecc32522-5799-48a6-93b2-0bf0b5d63ca2)

This causes CI's tests to be flaky.

### Desired behavior

Our CI tests should not be testing external links that are used in the codebase. Rather they should be tested using a synthetic monitor such as suggested by @adschwartz .
https://docs.datadoghq.com/synthetics/

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by leoporoli** [comment]
it was fixed here: https://github.com/kurtosis-tech/kurtosis/pull/1974/files
