### ISSUE TITLE
support headers in `plan.request` and `plan.wait`

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1971]
### Background & motivation

I am trying to make an http request and get some data but this API is behind bearer tokens; I now have to create a python script for thsi

### Desired behaviour

support headers in plan.request

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by h4ck3rk3y** [comment]
Franjo from DIVA echo'd this

**Comment by franjoespejo** [comment]
Thank you @h4ck3rk3y !
