### ISSUE TITLE
Enable tains/tolerations on k8s

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2048]
### Background & motivation

In order to enable smart scheduling (e.g placing EL/CL on the same host), it would be great if the service field could be extended with kubernetes [taints/tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/).

### Desired behaviour

Have an extra field in services for tolerations that takes a yaml array. 

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by mieubrisse** [comment]
Related (maybe duplicate?) of #2073
