### ISSUE TITLE
[FR]: Deserialize `args` object as a dictionary, not a struct

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#205]
### Background and motivation

I'm building the quickstart, and the `args` object is a top-level struct, but nested objects are dictionaries. This is very confusing.

### Current behavior

`args` object is a struct

### Desired behavior

`args` object, and all its nested objects, are dictionaries

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
This turns out to be especially important for checking if the user set an optional value.
```
if args.some_value == None:
```
throws an interpretation error on `some_value` not existing.

**Comment by victorcolombo** [comment]
This is a great point, IMO we should deliver this before we announce Kurtosis given that is a pretty brutal breaking change.

**Comment by mieubrisse** [comment]
@victorcolombo areas to ensure things are changed:
- everywhere in awesome-kurtosis
- all the code blocks in the quickstart
- all the packages on https://github.com/kurtosis-tech?q=package+in%3Aname&type=all&language=&sort=
