### ISSUE TITLE
The catalog truncates on large monitors

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#2061]
### What's your CLI version?

0.86.6

### Description & steps to reproduce

<img width="1891" alt="Screen Shot 2024-01-18 at 15 44 58" src="https://github.com/kurtosis-tech/kurtosis/assets/1142185/fd3390ca-3039-4078-a33a-c8abf1cfdaf9">

### Desired behavior

Probably, just make it extend the full width. I do know that it might (?) mess up spacing inside the app itself (or not? not sure)

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by Dartoxian** [comment]
Hey @mieubrisse the entire emui was designed for a fixed screen width - and this screenshot matches the designs. Just breaking this component out to be full width is a bigger change than it seems unfortunately. 

IMO the entire app feels 'truncated' on larger monitors - and my preference would be to keep the current app width, but center the main content - however this wouldn't actually address your concern with the horizontal rails being truncated: the choice of using a horizontal rail to display content like this means it will still be truncated even if it was stretched to your full screen width.

**Comment by Dartoxian** [comment]
Hey @mieubrisse , here is how the app would look on a larger monitor with centered main content.

[Screencast from 22-01-24 17:25:05.webm](https://github.com/kurtosis-tech/kurtosis/assets/4419574/dcc3fe9d-3c63-4116-be56-8f66605b822f)

**Comment by mieubrisse** [comment]
LGTM; I say do it
