### ISSUE TITLE
Backend support for `runStarlarkScript` in the EMUI

### ISSUE THREAD

**Issue by Dartoxian** [kurtosis-tech/kurtosis#2095]
### Background & motivation

@mieubrisse has suggested an experimental project for defining enclaves via a GUI. Services will be visually represented as a graph. It will be possible to convert the graph to a starlark script within the EMUI, which ideally should be able to execute the script in the same way it can execute packages.

Currently the EMUI connecting via the `connect-es` api can only execute published starlark packages via `runStarlarkPackage`.

### Desired behaviour

In order to execute the starlark script the EMUI needs to be able to call an endpoint like `runStarlarkScript`. I think adding this to the `enclave-manger` api would be the quickest way to unlock this behaviour in the EMUI.

The REST api seems to support this on the `/enclaves/{enclave_identifier}/starlark/scripts` endpoint. Should this endpoint be used? (how? do we pickup #1950?)

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
Done in #2103
