### ISSUE TITLE
Error in pulling Image in Kubernetes on mac os

### ISSUE THREAD

**Issue by shanithkk** [kurtosis-tech/kurtosis#2097]
### What's your CLI version?

0.86.12

## Description
Failing to pull the linux/amd64 container in mac os (arm64).

## Steps to reproduce
1. Setup the kubernetes 
2. install minikube
3. minicube start
4. update the kurtosis-config.yaml
5. change the clister to minikube (kurtosis cluster set minikube)
6. clone the repository https://github.com/HugoByte/polkadot-kurtosis-package.git
7. run the command 
 `kurtosis run . --args-file ./config.json --enclave polkadot`

## Screenshot
![Screenshot 2024-01-30 at 4 22 45 PM](https://github.com/kurtosis-tech/kurtosis/assets/59169878/3817ee81-6a7d-45c7-9bb7-4521bc3c7d5e)

### Desired behavior

parity/polkadot imgae shoul pull automatically and run the node

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by mieubrisse** [comment]
Confirming I saw this live; the image is `parity/polkadot:latest` [that exists on Dockerhub](https://hub.docker.com/layers/parity/polkadot/latest/images/sha256-109fee4ba2175002e6309d64e4f4d0455184e63c70900a08aaa50815c428e062?context=explore)

**Comment by mieubrisse** [comment]
I can repro this with this particular image on Minikube on ARM Mac:
```
kurtosis run github.com/kurtosis-tech/postgres-package '{"image":"parity/polkadot:latest"}'
INFO[2024-01-30T10:40:32-03:00] Engine running in Kubernetes cluster, to connect to the engine from outside the cluster run 'kurtosis gateway' to open a local gateway to the engine
INFO[2024-01-30T10:40:32-03:00] Creating a new enclave for Starlark to run inside...
INFO[2024-01-30T10:40:36-03:00] Enclave 'pretty-field' created successfully

Container images used in this run:
> parity/polkadot:latest - locally cached

> add_service name="postgres" config=ServiceConfig(image="parity/polkadot:latest", ports={"postgresql": PortSpec(number=5432, application_protocol="postgresql")}, files={"/data/": Directory(persistent_key="data-postgres")}, cmd=[], env_vars={"PGDATA": "/data//pgdata", "POSTGRES_DB": "postgres", "POSTGRES_PASSWORD": "MyPassword1!", "POSTGRES_USER": "postgres"}, max_cpu=1000, min_cpu=10, max_memory=1024, min_memory=32)
There was an error executing Starlark code
An error occurred executing instruction (number 1) at github.com/kurtosis-tech/postgres-package/main.star[112:40]:
  add_service(name="postgres", config=ServiceConfig(image="parity/polkadot:latest", ports={"postgresql": PortSpec(number=5432, application_protocol="postgresql")}, files={"/data/": Directory(persistent_key="data-postgres")}, cmd=[], env_vars={"PGDATA": "/data//pgdata", "POSTGRES_DB": "postgres", "POSTGRES_PASSWORD": "MyPassword1!", "POSTGRES_USER": "postgres"}, max_cpu=1000, min_cpu=10, max_memory=1024, min_memory=32))
  Caused by: Unexpected error occurred starting service 'postgres'
  Caused by: An error occurred creating pod 'postgres' using image 'parity/polkadot:latest'
  Caused by: An error occurred waiting for pod 'postgres' to become available
  Caused by: Container 'user-service-container' using image 'parity/polkadot:latest' in pod 'postgres' in namespace 'kt-pretty-field' is stuck in state 'ImagePullBackOff'. This likely means:
  1) There's a typo in either the image name or the tag name
  2) The image isn't accessible to Kubernetes (e.g. it's a local image, or it's in a private image registry that Kubernetes can't access)

Error encountered running Starlark code.
```

**Comment by mieubrisse** [comment]
Debugged with Shanith - seems like this is an issue of the image not having an ARM version published, and Minikube is hard-blocking it (because the same package works on Docker).

**Comment by laurentluce** [comment]
AFAIK there is no option to force K8S to pull for a specific arch.  The image above will have to be published with a manifest containing the list of supported archs.  This can be done with Docker buildx: `--platform linux/arm64/v8,linux/amd64`.

**Comment by mieubrisse** [comment]
@laurentluce could we add a third case to the error condition above, saying that the image's architecture might not match? I think we can close this ticket then
