### ISSUE TITLE
 kurtosis enclave dump on kubernetes should return files/artifacts/etc 

### ISSUE THREAD

**Issue by parithosh** [kurtosis-tech/kurtosis#2108]
### Background & motivation

currently the enclave dump is quite barebones, would be nice if all the relevant files are in to make it easier to debug

### Desired behaviour

show all files related to enclave irrespective of its k8s or docker

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by galenmarchetti** [comment]
thanks for the ticket @parithosh  ! looking into how much this would take to implement
