### ISSUE TITLE
FR: Allow me to not wait for pod termination in k8s

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2140]
### Background & motivation

For each task, a new pod is spun up. When this tasks completes (within a couple of seconds), the pod needs to wait for termination, which can take up to 30 seconds. 

While I understand that this feature is there to ensure that each run will stay deterministic, I'd prefer if there would be a way I could pass an extra flag during runtime where I can specify not to wait for termination.

Note: This is only relevant with k8s backend.

### Desired behaviour

`kurtosis run . --fast-mode...` would enable pods to be created, and proceed to the next plan item before waiting for pod termination. 

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by galenmarchetti** [comment]
thanks for submitting a suggestion for design here, as well - i like it. ensures deterministic runs at the level of package definition while giving the end user a way to break the assumptions for a faster run, understanding you might get breakage running it 👍 checking how hard this would be

**Comment by tedim52** [comment]
Hey @barnabasbusa here's a PR for that: https://github.com/kurtosis-tech/kurtosis/pull/2153

**Comment by h4ck3rk3y** [comment]
Closed by @tedim52
