### ISSUE TITLE
StoreSpec is not defined in the docs

### ISSUE THREAD

**Issue by Dartoxian** [kurtosis-tech/kurtosis#2146]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/api-reference/starlark-reference/plan

### Issue description

`StoreSpec` is mentioned on https://docs.kurtosis.com/api-reference/starlark-reference/plan, but there is no Starlark reference for it.

**Comment by galenmarchetti** [comment]
thanks for catching this @Dartoxian , going to schedule a docs cleanup cycle and to tackle this and some others
