### ISSUE TITLE
Explain to the user what's going to happen when they do `kurtosis github login`

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#2181]
### Background & motivation

I ran `github login` and pressed Enter (so good so far). However, when I got to Github, it said "Enter the code displayed on your device". I was confused - no notification had popped up on my Mac, nor on my phone.

Only after a few seconds did I realize "device" meant the Kurtosis terminal here. 

### Desired behaviour

Before Github is opened, the user gets a short explanation of what's going to happen so they understand what to do.

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by mieubrisse** [comment]
I also just realized that it said "first copy your one-time code", but I completely skipped that step seeing only "Press ENTER to open Github". Maybe not proceeding until they copy the code, with an explanation that when Github asks for "device" it means that code?

**Comment by tedim52** [comment]
Addressed in https://github.com/kurtosis-tech/kurtosis/pull/2193
