### ISSUE TITLE
After `github login`, the engine needs to be restarted but there's no direction for this

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#2183]
### What's your CLI version?

0.86.25

### Description & steps to reproduce

After doing a `github login` I retried my private package but got another failure. After talking with @tedim52 on Slack, it looks like the engine needs to be restarted.

### Desired behavior

The `github login` process walks me through everything that I need to do, including restarting the engine. Ideally, I even have the option to restart the engine right then as part of the `github login` flow. 

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by tedim52** [comment]
This PR solves this by automatically restarting the engine after successful login: https://github.com/kurtosis-tech/kurtosis/pull/2193
