### ISSUE TITLE
[FR]: Add new `kurtosis feedback` flags 

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#219]
### Background & current behavior

When I run: `kurtosis feedback "my feedback" --github`, I end up on the Github issues page where I then have to use the Github UI to select what kind of Issue to file (docs, feature request, or bug report).

More often than not, I already know what kind of Github issue I want to file. Being able to specify my preferred feedback route using a flag to pass into the `kurtosis feedback` command would make it easier and smoother for me to submit feedback to the Kurtosis team.

### Desired behavior

I would like to see 3 new flags added to the `kurtosis feedback --github` command:

1. When I run: `kurtosis feedback "my feedback" --github --bug` a Github link opens up to the Bug Report Github issue template with the "Description and steps to reproduce" section pre-populated with "my feedback" ([example](https://github.com/kurtosis-tech/kurtosis/issues/new?assignees=&description=my+feedback&labels=bug&metrics-user-id=07d14724970e58810d93e5520436603ca4c113ad9bd608bec371f9122534cf4b&template=bug-report.yml&title=%5Bbug%5D%3A+&version=0.68.11))
2. When I run: `kurtosis feedback "my feedback" --github --fr` a Github link opens up to the Feature Request Github issue template with the "Background and current behavior" section pre-populated with "my feedback" ([example](https://github.com/kurtosis-tech/kurtosis/issues/new?assignees=&background-and-motivation=my+feedback&labels=feature+request&template=feature-request.yml&title=%5BFR%5D%3A+)).
3. When I run: `kurtosis feedback "my feedback" --github --docs` a Github link opens up to the Docs Issue Github issue template with the "Description of the issue" section pre-populated with "my feedback" ([example](https://github.com/kurtosis-tech/kurtosis/issues/new?assignees=leeederek&description=my+feedback&labels=docs&template=docs-issue.yml&title=%5BDocs%5D%3A+)).

### How important is this feature or improvement to you?

Painful, the lack of this feature makes using Kurtosis frictionful.

**Comment by mieubrisse** [comment]
@leeederek very aligned; when building the quickstart I used `--github` a LOT. I actually didn't send any emails because I was afraid they would get lost in the shuffle.

Wdyt if:
- github is the default action of `kurtosis feedback`
- raw `kurtosis feedback` takes the user to the New Github Issue page
- all the flags work as you describe
- the same `--fr`/`--bug`/`--docs` command are used with the `--email` flag (but just to set the subject prefix)?

**Comment by leeederek** [comment]
Hey @mieubrisse! Thanks for your feedback. I'm going to keep this Issue tightly scoped to the work required for adding new flags, and have created #226 to track the work required to swap the default operation in `kurtosis feedback` from Email to Github 👍🏻!
