### ISSUE TITLE
[FR]: Simplify bug report form

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#221]
### Background & current behavior

When doing the quickstart, I often didn't use the "relevant log output" field, and it was a little unclear how to work it into me describing the issue. I think we should probably do away with it entirely, and purely ask users to provide log output in the "Description & steps to reproduce"

Conversely, I _do_ think it would be valuable to have an optional "`enclave dump` output" field with steps for producing an `enclave dump` and attaching it, so that users realize they can do it and so we get the full debugging package. 

https://github.com/kurtosis-tech/kurtosis/issues/177 is a good example in action: I had several log outputs to report (so a single "relevant log output" field doesn't suffice), and I didn't have a place to attach the enclave dump output so I just shoved it into the Description.

### Desired behavior

"relevant log output" is replaced by a filepicker (if possible) or some dedicated field for the user to upload their `enclave dump`, so that we're encouraging them to do so.

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by leeederek** [comment]
Hey @mieubrisse: great feedback. 

Re: updating the bug report template - I've gone ahead and made it way more explicit and straight forward for a user to know what types of logs we want to see from them (enclave dump logs to be exact). I also added a few hyperlinks to make it a bit smoother to learn about `enclave dump` and `metrics philosophy` here: https://github.com/kurtosis-tech/kurtosis/pull/237

Re: filepicker for uploading logs - I had a look at the supported input types for [Github Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) and unfortunately file-upload is not one of them. To support that functionality, we may have to look at doing this from the CLI itself (tracked in #179, thank you for that).
