### ISSUE TITLE
Detect & attach `application_protocol = http` to appropriate ports from transpiled Compose

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#2213]
### Background & motivation

Right now, transpiled Compose files don't get any `application_protocol` which makes them unclickable & unviewable in the frontend.

### Desired behaviour

Transpilation autodetects web ports and attaches `application_protocol = http` to them. Maybe by doing it for any port that's 80, 8080, or 8000?

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by tedim52** [comment]
Addressed by: https://github.com/kurtosis-tech/kurtosis/pull/2281
