### ISSUE TITLE
Cloud: Some of these keys are not valid for this package

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2229]
### What's your CLI version?

0.87.2

### Description & steps to reproduce

<img width="890" alt="Screenshot 2024-02-27 at 23 37 03" src="https://github.com/kurtosis-tech/kurtosis/assets/21987084/b250c93d-a1a3-4b08-b4f0-3190e1e5a8c5">
Create a new enclave in the webui, and add some yaml to configure it. Select yaml on top bar. 

### Desired behavior

Run the custom enclave. 

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment]
hey @barnabasbusa , this is because the ETH package just has a single argument called `args`: https://github.com/kurtosis-tech/ethereum-package/blob/main/main.star#L54 If you split these out into separate args, it'll work. Otherwise, you'll have to put these nested under a root-level `args:` key.

**Comment by mieubrisse** [comment]
Example: https://github.com/kurtosis-tech/hyperlane-package/blob/main/main.star#L6

**Comment by mieubrisse** [comment]
@barnabasbusa does this answer your question? can we close?
