### ISSUE TITLE
Cloud: Error: ConnectError: [unknown] Load failed

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2231]
### What's your CLI version?

0.87.2

### Description & steps to reproduce

<img width="1352" alt="Screenshot 2024-02-27 at 23 47 57" src="https://github.com/kurtosis-tech/kurtosis/assets/21987084/6bd05a4f-40e6-43f5-86b3-865e02c03f85">

I have added no customization. Just ran a random ethereum-package with no configuration. 

### Desired behavior

I should be able to run an enclave. 

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by leoporoli** [comment]
closing this one, because we are tracking it here: https://github.com/kurtosis-tech/kurtosis/issues/2176 @barnabasbusa
