### ISSUE TITLE
feat: HTTP traffic should be routable to the user services using more than one Host header format

### ISSUE THREAD

**Issue by laurentluce** [kurtosis-tech/kurtosis#2268]
### Background & motivation

The request Host header reaching the user service should match the original request Host header so URLs generation and redirects work correctly.  This should happen locally and in the cloud.

### Desired behaviour

Traefik routes http traffic to the user services.  The user service Host header label should accept the following two formats:
- `<port number>.<service short uuid>.<enclave short uuid>`
- `<port number>.<service short uuid>.<enclave short uuid>.<cloud instance short uuid>.<subdomain>`

Method to update: https://github.com/kurtosis-tech/kurtosis/blob/c640c5eae57429de2a827e64de0175a111fc298d/container-engine-lib/lib/backend_impls/docker/object_attributes_provider/enclave_object_attributes_provider.go#L533

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by leoporoli** [comment]
It was fixed with those PRs, and it supports retro-compatibility.

**Comment by daramir** [comment]
@leoporoli was this tested?
I'm not sure if the Traefik Golang Regexp for Host matching 
```
HostRegexp(`{^name:%d-%s-%s-?%s$}`)
``` 

is correct?

Is the caret in  `^name` part of the  ["arbitrarily named variable followed by the colon-separated regular expression"](https://doc.traefik.io/traefik/v2.0/routing/routers/)? 

I have a kurtosis setup running on docker that I would like to use the reverse proxy feature for, but it's unusable... I'm unable to reach those hosts on the Traefik configured routes.
