### ISSUE TITLE
Make `scripts/versions_check.sh` tool-agnostic

### ISSUE THREAD

**Issue by leovct** [kurtosis-tech/kurtosis#2270]
### Background & motivation

The `scripts/versions_check.sh` script, which is triggered when building a local binary of Kurtosis, expects `nvm` to be installed. As there are other ways to install a local version of `node` (e.g. [asdf](https://github.com/asdf-vm/asdf-nodejs)), it would be nice to make the script tool-agnostic.

The quick hack I've found to be able to build the local binary is simply to prevent the `versions_check` script from being called by commenting it out in `scripts/build.sh` :)

### Desired behaviour

I would like to be able to build a local Kurtosis binary without having to modify `scripts/build.sh`.

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by mieubrisse** [comment]
This makes a lot of sense, @leovct . We should probably do something like `node --version` instead (the actual thing that needs testing, rather than proxying via `nvm`)
