### ISSUE TITLE
[FR]:  Kurtosis version prints both the CLI and the engine versions

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis#232]
### Background & current behavior

Engineers go to `kurtosis version` to understand whether they have version mismatches between installations, and in order to truly check this, they'd have to go to both `kurtosis version` and `kurtosis engine status` - which requires a more advanced/in-depth understanding of kurtosis architecture and version management

### Desired behavior

Engineers only have to go to `kurtosis version` to fully understand the kurtosis versions they're running

### How important is this feature or improvement to you?

Painful, the lack of this feature makes using Kurtosis frictionful.

**Comment by leeederek** [comment]
Hey @galenmarchetti! This makes sense. Would you find it valuable for `kurtosis version` to also print upgrade instructions when there are discrepancies in the versions? Specifically, I would like to propose the following implementation/prototype:

1. If kurtosis cli version = latest AND != kurtosis engine version, recommend a `kurtosis engine restart`
2. If kurtosis cli version != latest AND != kurtosis engine version, recommend an upgrade & engine restart

What do you think?
