### ISSUE TITLE
Get All Services

### ISSUE THREAD

**Issue by minhd-vu** [kurtosis-tech/kurtosis#2349]
### Background & motivation

I'm currently working with the [prometheus](https://github.com/kurtosis-tech/prometheus-package) and [grafana](https://github.com/kurtosis-tech/grafana-package) packages, and I would like an easier way to fetch all of the services to create the `metrics_jobs` input for prometheus. Right now, I'm using `plan.get_service` to fetch all of the services, but I'm facing some friction where I'll detail with the example below.

```starlark
def run(plan, args):
    # These functions conditionally deploy services and don't return the service
    # object. Either, both, or none of the services can be deployed.
    conditionally_deploy_service_a()
    conditionally_deploy_service_b()

    services = []
    service_names = [
        "service-a",
        "service-b",
    ]

    for name in service_names:
        # Because the services can be conditionally deployed, the get_service 
        # call can fail. I don't believe there is a way to catch an error in 
        # startosis.
        service = plan.get_service(name=name + args["deployment_suffix"])
        services.append(service)

    metrics_jobs = [
        {
            "Name": service.name,
            "Endpoint": "{0}:{1}".format(
                service.ip_address,
                service.ports["prometheus"].number,
            ),
        }
        for service in services
    ]

    prometheus_url = prometheus_package.run(plan, metrics_jobs)
```

### Desired behaviour

Here, I would like something like a `get_all_services` that will fetch all of the active services in the enclave. Do you know if this would be possible?

```starlark
def run(plan, args):
    conditionally_deploy_service_a()
    conditionally_deploy_service_b()

    services := plan.get_all_services()

    metrics_jobs = [
        {
            "Name": service.name,
            "Endpoint": "{0}:{1}".format(
                service.ip_address,
                service.ports["prometheus"].number,
            ),
        }
        for service in services
    ]

    prometheus_url = prometheus_package.run(plan, metrics_jobs)
```

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

SDK: the Software Development Kit libraries - Typescript, Go, etc.

**Comment by tedim52** [comment]
@minhd-vu this instruction should be released on latest: [feat: get all services (](https://github.com/kurtosis-tech/kurtosis/commit/2ba98f5f3d82ffd099cda0942ee358fe02bc70a5)

**Comment by minhd-vu** [comment]
I tried testing it out but the behavior isn't what I expected. Here's what I'm doing:
```starlark
def run(plan, args):
    conditionally_deploy_service_a()
    conditionally_deploy_service_b()

    services := plan.get_services()

    metrics_jobs = [
        {
            "Name": service.name,
            "Endpoint": "{0}:{1}".format(
                service.ip_address,
                service.ports["prometheus"].number,
            ),
        }
        for service in services
    ]

    prometheus_url = prometheus_package.run(plan, metrics_jobs)
 ```

But I'm getting a similar error to:

```
There was an error interpreting Starlark code
Evaluation error: key "prometheus" not in dict
	at [github.com/0xPolygon/kurtosis-cdk/main.star:187:34]: run
	at [github.com/0xPolygon/kurtosis-cdk/observability.star:57:30]: run

Error encountered running Starlark code.
```

What I think is happening is that the `plan.get_services()` is being evaluated before either of the conditional services are created, so the `get_services()` call returns nothing. Let me know if you can reproduce or need additional clarification.

**Comment by tedim52** [comment]
Hey @minhd-vu ! Are you seeing that the `services` object is empty? (can verify with `plan.print(len(services))` or smth)? I believe the source of `key "prometheus" not in dict` error could be from the fact that one of the `services` does not have a port with id `prometheus` so the `service.ports["prometheus"].number` call is breaking.

**Comment by minhd-vu** [comment]
Ah yes! 🤦 I overlooked this. It seems to be working as expected now, thanks for the help!
