### ISSUE TITLE
[FR]: build script should check for the presence of expected node and go version

### ISSUE THREAD

**Issue by eliziario** [kurtosis-tech/kurtosis#239]
### Background & current behavior

As I tried to build the project for the first time, yarn install failed because I was using an incompatible version of node

### Desired behavior

It would be interesting if scripts/build.sh checked for specific versions of node and go. 

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by h4ck3rk3y** [comment]
Thanks @eliziario for your contribution!
