### ISSUE TITLE
Kurtosis can't run linuxserver/wireguard

### ISSUE THREAD

**Issue by jshufro** [kurtosis-tech/kurtosis#2405]
### What's your CLI version?

0.88.18

### Description & steps to reproduce

Putting:
```
plan.add_service(name = 'wireguard', config = ServiceConfig(image="linuxserver/wireguard",ports={"docker-51820": PortSpec(number=51820,transport_protocol="UDP",wait="30s")},files={"/config/wg0.conf": wg_conf},entrypoint=[],cmd=[],env_vars={"PUID": "1000","PGID": "1000","TZ": "Etc/UTC"}))
```
in main.star leads kurtosis to fail to start a perfectly good docker container with the following error:
`s6-overlay-suexec: fatal: can only run as pid 1`

I believe this is because of https://github.com/kurtosis-tech/kurtosis/commit/b8989a8112e4f25fed0e595d32a28c45a58a8b1b

Is there a way to turn off the use of docker `--init`?

### Desired behavior

Wireguard should start

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by Jiangzy520** [comment]
@jshufro Sir, you can leave your email address. I want to ask you questions

**Comment by h4ck3rk3y** [comment]
hey @jshufro Gyani from Kurtosis here. Thank you for writing this ticket.

We don't support disabling tini out of the box and will have to add support for it. Can you tell me more about your usecase?

In the meantime I will try to compile a version of Kurtosis with tini disabled and run your script

**Comment by h4ck3rk3y** [comment]
Looking at your main.star further

Can you try removing ENTRYPOINT CMD set to [] and see if it runs? It has to have something for it to run. Not setting them is using the default values

```
def run(plan):
    plan.add_service(name = 'wireguard', config = ServiceConfig(image="linuxserver/wireguard",ports={"docker-51820": PortSpec(number=51820,transport_protocol="UDP",wait="30s")},env_vars={"PUID": "1000","PGID": "1000","TZ": "Etc/UTC"}))
```

this works just fine. You will have to add back wg_conf;

**Comment by jshufro** [comment]
EDIT: never mind, I still see:

```There was an error executing Starlark code 
An error occurred executing instruction (number 46) at github.com/nodeset-org/nodeset-testnet/main.star[17:21]:
  add_service(name="wireguard", config=ServiceConfig(image="linuxserver/wireguard", ports={"docker-51820": PortSpec(number=51820, transport_protocol="UDP", wait="30s")}, files={"/config/wg0.conf": "wireguard-config"}, env_vars={"PGID": "1000", "PUID": "1000", "TZ": "Etc/UTC"}))
  Caused by: Unexpected error occurred starting service 'wireguard'
  Caused by: An error occurred starting the user service container for user service with UUID '2a9763e8c89d4972ae8a642d9b33c040'
  Caused by: An error occurred checking if container '2699bbd4cb48f055dd6212ce8b8020246446a5f00af2128897fade9d29b5966f' is running
  Caused by: Container '2699bbd4cb48f055dd6212ce8b8020246446a5f00af2128897fade9d29b5966f' (with image 'linuxserver/wireguard:latest') die with a non zero exit code rapidly after it was started. This likely indicates a misconfiguration with how the container was started. Container should either exit gracefully or keep running for Kurtosis to consider it in a good state; logs are below:
  --------------------- CONTAINER LOGS -----------------------
  0s6-overlay-suexec: fatal: can only run as 
  ------------------- END CONTAINER LOGS --------------------

Error encountered running Starlark code.

```

**Comment by h4ck3rk3y** [comment]
Interesting, I am pretty sure I could get it to run on Friday but now I can confirm that I am seeing what you are seeing.

More over this change - https://github.com/kurtosis-tech/kurtosis/pull/2412 seems to get it to work but we would like to put it behind a Starlark interface so that users can switch it on/off willingly. 

Can you tell me more about your usecase?

**Comment by h4ck3rk3y** [comment]
@jshufro this should solve it - https://github.com/kurtosis-tech/kurtosis/pull/2425

**Comment by h4ck3rk3y** [comment]
@jshufro 0.89.4 should have the `tini_enabled` option;

https://github.com/kurtosis-tech/kurtosis/pull/2431
