### ISSUE TITLE
[bug]: explore erroring if the cli version > engine version

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#244]
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.68.12

### What is the severity of this bug?

Papercut, this bug is frustrating, but I have a workaround.

### Description & steps to reproduce

https://kurtosistech.slack.com/archives/C04B5FXNKU4/p1679056457822239

### Desired behavior

Figure out whether the current behavior is okay or error away and exit

**Comment by leeederek** [comment]
Also related: #234 and #232
