### ISSUE TITLE
[bug]: An unknown image is used to start a Kurtosis engine (when performing a fresh engine start)

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#255]
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.68.13

### (Optional) What is your metrics user ID?

07d14724970e58810d93e5520436603ca4c113ad9bd608bec371f9122534cf4b

### What is the severity of this bug?

Papercut, this bug is frustrating, but I have a workaround.

### Description & steps to reproduce

When I start a fresh Kurtosis engine, the following gets printed:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/103802618/226214258-1291181c-0356-4c6e-a718-9bc7211df2b9.png">

The `from image ''...` looks like a bug/typo. I'm not entirely sure what it means nor does it make me feel like everything performing as intended. Can we remove it or make it more obvious what's happening? 

### Desired behavior

When I start, upgrade, or re-install Kurtosis, its clear to me what images are being pulled (or abstract that away from the user entirely).

**Comment by adschwartz** [comment]
I ran into this issue as well. Made me pause...

**Comment by h4ck3rk3y** [comment]
I think this has always been the case when you use `kurtosis engine start` the "''" indicates that custom version hasn't been found. I'll fix the messaging on this as this can be confusing 👍
