### ISSUE TITLE
Fluentbit configurator sticks around when creating enclaves concurrently and prevents new enclaves from being created

### ISSUE THREAD

**Issue by mslipper** [kurtosis-tech/kurtosis#2568]
### What's your CLI version?

1.3.0

### Description & steps to reproduce

When multiple processes try to create enclaves at the same time, sometimes the fluentbit configurator container sticks around. This then causes subsequent creations to fail. You can see an example of this here: https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/68789/workflows/125efdd1-ffc2-4034-8517-80a841d856d2/jobs/2846767/parallel-runs/0/steps/0-104. 

I tried my hand at fixing this here by adding a suffix to the container name: https://github.com/kurtosis-tech/kurtosis/pull/2567.

### Desired behavior

Concurrent enclaves should be created successfully.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

Other: anything not covered by the above

**Comment by tedim52** [comment]
Ah I checked out the issue - I do think adding the suffix should solve the issue. Will take a look at your PR : )
