### ISSUE TITLE
Using `run_sh` output in "description" arg results in a future reference string

### ISSUE THREAD

**Issue by MegaRedHand** [kurtosis-tech/kurtosis#2571]
### What's your CLI version?

1.3.1

### Description & steps to reproduce

I'm using `run_sh` to get a value from a JSON file artifact. I later use the output in the description of a call to `run_sh` that uses that value. This description contains a reference string instead of the runtime value:

```
... {{kurtosis:195f3ae3b53a4f83979445a725695a37:output.runtime_value}}
```

A workaround would be to print the value, but it's not the same.

### Desired behavior

I expected the reference string to be replaced with the runtime value.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by tedim52** [comment]
Ah so the descriptions are created and populated at interpretation time, and at that time the value isn't known. Curious if there's a reason you'd like to use that value in a description as opposed to a print?

**Comment by MegaRedHand** [comment]
Just because the info is related to the command in the `run_sh`.
I'm generating a value with the first `run_sh` and later acting on that value inside the second `run_sh`, so I was trying to somehow convey that information, but it's true that it _can_ be done with a `print`. I was unsure if this was intended or not, so I marked it as `bug`.
