### ISSUE TITLE
Command run with `run_sh` failing silently

### ISSUE THREAD

**Issue by MegaRedHand** [kurtosis-tech/kurtosis#2576]
### What's your CLI version?

1.3.1

### Description & steps to reproduce

When running `kurtosis run main.star` with the following minimal package:

```starlark
# main.star
def run(plan, args={}):
    plan.run_sh(run="exit 1")
```

I get the following output:

```
INFO[2024-10-29T17:54:19-03:00] Creating a new enclave for Starlark to run inside... 
INFO[2024-10-29T17:54:21-03:00] Enclave 'vast-fen' created successfully      

Container images used in this run:
> badouralix/curl-jq - locally cached

Running sh script: `exit 1`
Command returned with exit code '0' with no output

Starlark code successfully run. No output was returned.

⭐ us on GitHub - https://github.com/kurtosis-tech/kurtosis
INFO[2024-10-29T17:54:24-03:00] ================================================= 
INFO[2024-10-29T17:54:24-03:00] ||          Created enclave: vast-fen          || 
INFO[2024-10-29T17:54:24-03:00] ================================================= 
Name:            vast-fen
UUID:            8d1a612efba9
Status:          RUNNING
Creation Time:   Tue, 29 Oct 2024 17:54:19 -03
Flags:           

========================================= Files Artifacts =========================================
UUID   Name

========================================== User Services ==========================================
UUID   Name   Ports   Status
```

### Desired behavior

I expected this command to fail after executing that step. Not failing right then propagates errors to other steps, sometimes with quite confusing results.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by tedim52** [comment]
Hey I'll take a look into this. Specifically wondering why the exit code is `0`. For now, I imagine you are running this against a specific workflow. Are you able to check the output of `result.output` and use that to fail instead?

**Comment by MegaRedHand** [comment]
Yes. For cases where we're not already using the output, we could append an `echo $?` or similar and `verify` it at the end. Otherwise, we'd need to parse the output first.

Also, just re-read the docs and it seems I mixed up the `run_sh` and `exec` commands. I thought both behaved the same wrt non-zero exit codes. Sorry for the confusion!

**Comment by tedim52** [comment]
awesome!
