### ISSUE TITLE
Segfault on latest release

### ISSUE THREAD

**Issue by klkvr** [kurtosis-tech/kurtosis#2580]
### What's your CLI version?

1.4.0

### Description & steps to reproduce

Our CI jobs started failing with a segfault after Kurtosis got updated to 1.4.0.

Failing run log:
https://github.com/paradigmxyz/reth/actions/runs/11604491194

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by xavier-romero** [comment]
Same issue here, unable to get it working with 1.4.0
![image](https://github.com/user-attachments/assets/d0f39c44-27bc-4bef-8f0e-e7a80e50f5a8)

**Comment by tedim52** [comment]
Hey this is a known issue we're on 1.4.0, we're working on releasing a fix ASAP! https://github.com/kurtosis-tech/kurtosis/pull/2579 For now please use 1.3.0 or earlier

**Comment by skylenet** [comment]
It's fixed now on the latest release `1.4.1` 👍
