### ISSUE TITLE
[Docs]: English typo on banner "schedule live session"

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis#270]
### Where did you see an issue in our documentation?

https://docs.kurtosis.com/

### Description of the issue

Right now the banner says:

- Schedule a live session with us to help getting started or to learn more.

Suggestion, we switch it to:

- Schedule "a call" with us "for" help getting started or to learn more

For two reasons:
1. Fix a grammar error, switching "to" to "for"
2. Switch "live session" to "a call" so that it communicates the flexibility of the call, ie no specific agenda other than to serve the user

**Comment by leeederek** [comment]
Hey @galenmarchetti , thanks for flagging! I've fixed the typo in the linked PR, but want to leave the wording as `live session`. Let me know what you think!
