### ISSUE TITLE
[FR]: Allow two packages to be developed locally

### ISSUE THREAD

**Issue by victorcolombo** [kurtosis-tech/kurtosis#355]
### Background & current behavior

Currently if package A depends on package B, it is impossible to have A run locally if B is also local.

Current workflow involves pushing B to Github, only then running A locally. This is especially painful given that if they are on mutual iteration (changes on A affect B and changes of B affect A).

An alternative workflow is develop A and B inside as if they were the same package, then breaking those up. This is also super painful because it it not sustainable for big packages.

### Desired behavior

Similarly to Go, we could offer a `replace` directive to point to a local package instead of the remote one

### How important is this feature or improvement to you?

Painful, the lack of this feature makes using Kurtosis frictionful.

**Comment by h4ck3rk3y** [comment]
Probably worth a product page that @victorcolombo will spin up

Requires Design it looks like

**Comment by mieubrisse** [comment]
design to build `replace` that allows for local package replacement: https://www.notion.so/kurtosistech/2023-09-Forked-Packages-Cleanup-d8bc4f5165ae4b039c07cdad56892459?pvs=4
