### ISSUE TITLE
[FR]: VSCode points the users to Kurtosis installation docs if `kurtosis` isn't installed

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#368]
### Background & current behavior

The VSCode plugin looks for `kurtosis`. Right now, it doesn't do anything if it doesn't find it.

### Desired behavior

If it doesn't find it, we should let the user a) know about it and b) point them to Kurtosis installation docs

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by victorcolombo** [comment]
Golang plugin does a similar thing suggesting the user to upgrade Go version 

<img width="471" alt="Screenshot 2023-04-03 at 10 39 08" src="https://user-images.githubusercontent.com/1737857/229472413-08b47910-61ac-4660-bc97-ea95e80796f5.png">

**Comment by h4ck3rk3y** [comment]
Lets investigate if we can solve this very quickly and if not we will revaluate the ticket
