### ISSUE TITLE
[FR]: Clean up `kurtosis files download` helptext

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#370]
### Background & current behavior

In [a user feedback session today](https://www.notion.so/kurtosistech/Aron-Kurtosis-8803338359824b56b94510fe5a9891f9?pvs=4) we saw a user struggle mightily getting `kurtosis files download` to work. He kept entering:
```
kurtosis files download enclave ....bunch of different attempts here...
```
and was very confused what a resource identifier is. We eventually determined:

1. Having the way to enter enclave be `--enclave` in `kurtosis run` but be a positional arg here was confusing to him and
2. The `enclave` string in the helptext was confusing to him
3. He wasn't sure what an identifier was (though it is in the helptext, to be fair - think the pressure of a quickstart experience session might have contributed)

### Desired behavior

Long:
```
Download the given files artifact from the given enclave to your machine. The files artifact and enclave are specified by identifier (name, UUID, or shortened UUID). Read more about identifiers here: https://docs.kurtosis.com/reference/resource-identifier
```

also the `enclave` argkey is replaced with `enclave-identifier`

(addressing the consistency of enclave arguments is something else percolating in my brain, for later)

### How important is this feature or improvement to you?

Painful, the lack of this feature makes using Kurtosis frictionful.

**Comment by h4ck3rk3y** [comment]
I'm not on this ticket but continuing our discussion from yesterday; is this a "breaking change" for you?

**Comment by mieubrisse** [comment]
@h4ck3rk3y nope - don't think the user has to take any action to fix, so not a breaking change
