### ISSUE TITLE
[FR]: Build a CLI command to print information about a port

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#372]
### Background & current behavior

Pretty much since the dawn of Kurtosis, the ephemeral, changing ports have been a thorn in the side of users. This is why we built the static-ports hack in Starlark. Today, [yet another user hit this](https://www.notion.so/kurtosistech/Aron-Kurtosis-pt-2-2-ddc2081a389144458c5972ef19343045?pvs=4).

Much better would be a way for the CLI to output the various port information, so the user has to think about it less. This probably won't fully replace the need for static ports, but it should help a lot (especially with the quickstart).

### Desired behavior

BASIC: the user can do `curl -XGET http://127.0.0.1:$(<something>)` and the port number is plugged in

ADVANCED: the user can do `curl -XGET $(something)` and the entire URL is plugged in

Talk to Kevin about this for solutioning; he has ideas!

### How important is this feature or improvement to you?

Painful, the lack of this feature makes using Kurtosis frictionful.

**Comment by gbouv** [comment]
@mieubrisse will that be needed in a world where we have static port bindings? It feels like it's a bandaid on something we might not be too too far from. Maybe if we prioritize the static port binding higher, we can provide a first class solution here. WDYT?

**Comment by mieubrisse** [comment]
I _think_ they move in orthogonal space, and are both necessary. This would be for, "I don't care about the port number; just give me the info" a la:
```
curl -XGET http://127.0.0.1:$(kurtosis port print my-enclave my-service my-port)
```
Static port bindings would be for something like, 'I have a config file that needs me to hardcode a port number'

And actually, whenever possible, I'd prefer folks use the `kurtosis port print` approach because it's more robust (even if the author changes the port number, you're protected)

**Comment by gbouv** [comment]
Got it got it, that makes sense to me. Let's do both then and focus on the cli command to retrieve the info for the scope of this ticket

As you said above, I think retrieving only the port is a bit sad here, we should rather retrieve the entire endpoint, including the scheme, host and port. 

So, if you were sold of "print", we can easily do:
```
> kurtosis service print --endpoint my-enclave my-service my-port
https://127.0.0.1:45243
> kurtosis service print --port-number my-enclave my-service my-port
https://127.0.0.1:45243
```

Another thought, I just reviewed a PR from Gyani where he was moving the from being an args to being a flag `--enclave my-enclave` Should we do the same here?

Let me know what you think of the proposals above. I do not feel super strongly about it, I tried to not add another root command to `kurtosis`, but whatever works with me.
I can action this pretty quickly so if you can either ACK with the above or post a full spec of what you'd like, we can probably get that in before the cut

**Comment by h4ck3rk3y** [comment]
@Peeeekay are you done with this?

**Comment by Peeeekay** [comment]
it's closed; the command is kurtosis port print <encalve> <service> <port>
