### ISSUE TITLE
[bug]: The enclave argument of `kurtosis service logs` doesn't have tab-complete enabled

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#373]
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.70.7

### (Optional) What is your metrics user ID?

0497e811755b8f775ef0d99cd22b1ef221708b5a95119857a310cbc4f2eabcae

### What is the severity of this bug?

Critical, I am blocked and Kurtosis is unusable to us because of this bug.

### Description & steps to reproduce

Type `kurtosis service logs <TAB>` with an existing enclave. Note that no completion happens. Service completion seems to be fine.

### Desired behavior

Enclave completion happens as expected.

**Comment by h4ck3rk3y** [comment]
It does have tab complete enabled but it doesn't work if you restart the engine as it stores uuid / name mapping in memory; wonder if we can change this and fetch everything from disk/docker

**Comment by h4ck3rk3y** [comment]
I have created #374 that is a best effort fix for this that gets all enclaves registered in the backend in case we our in memory map returns empty (no enclaves registered / restart); longer fix here is to persist identifiers as this doesn't get your removed enclaves for which we might still have logs

**Comment by h4ck3rk3y** [comment]
For context @Peeeekay ran into this while demo'ing pari
