### ISSUE TITLE
[FR]: Print enclave name when running `kurtosis clean -a` (in addition to the UUID)

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#38]
## Observed Behavior
When I run `kurtosis clean -a` with a running or stopped enclave, Kurtosis will remove all artifacts and prints out the enclave UUID.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/103802618/220466475-2211a651-4a95-4b99-ae30-3aa26fe431ed.png">

## Expected Behavior
I'd like to be able to see the UUID and the names of the artifacts that were cleaned. 

## Why
Printing both the UUID and the name of the artifacts that were cleaned helps with readability and makes the print outputs more consistent with other commands, such as `kurtosis enclave ls`. `kurtosis service add` and `kurtosis enclave inspect` which prints out both UUID and names for enclaves and containers.

Example output of `kurtosis enclave inspect`: 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/103802618/220466937-4946a7b3-f982-412c-840a-4733a04281dc.png">

Example output of `kurtosis enclave ls`:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/103802618/220467052-8c5040c1-4318-47e2-88fc-a7597e4c500f.png">

Example output of `kurtosis service add`:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/103802618/220467091-f095c936-3311-439e-9774-b7dc821a7343.png">

**Comment by adschwartz** [comment]
@leeederek Not sure if this is a problem or not but if you list all the enclaves that have been cleaned up it could potentially be a large list. Not sure if this is a problem, but I wonder why it was the way it is today. Have we checked with @mieubrisse if it was made this way for any particular reason? If not then I'm totally fine with working this ticket. let me know
