### ISSUE TITLE
Remove `kurtosis config init` command

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#435]
### Background & current behavior

The `kurtosis config init` is a remnant from old days, with how we used to initialize the config. We can remove it now.

### Desired behavior

The `kurtosis config init` command no longer exists, and the docs (particularly "Running in CI" have been updated appropriately)

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

**Comment by h4ck3rk3y** [comment]
Might be good to merge as Waku / Eth don't use this.
