### ISSUE TITLE
Replace all uses of "partitioning" in the client libraries with "subnetworking"

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#443]
### Background & motivation

"Partitioning" is a dated term; this should now be called "subnetworking".

I found at least one instance in `KurtosisContext.createEnclave`

### Desired behaviour

All references to "partitioning" are now switched to "subnetworking".

Docs are appropriately.

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
@victorcolombo I'm seeing `addServiceToPartition` in the client libraries; these can be killed right because it's now all in Starlark? (maybe @leoporoli this is what your Q2P1 project suggestion is about?)

**Comment by h4ck3rk3y** [comment]
Fix docs and client libraries
