### ISSUE TITLE
docs: Add sub categories to the exploded output of "Starlark Reference"

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#456]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/starlark-reference/plan

### Issue description

I can't quite tell what I am looking at here and this is quite confusing for me

<img width="321" alt="image" src="https://user-images.githubusercontent.com/6670312/229496049-931aec8f-cf82-4d02-9c5d-14b47c356f0f.png">

I'd like something more informative as a quick example - 

```
Starlark Reference/
   Kurtosis Types/
      ConnecitonConfig
      NormalPacketDistribution
   Non Plan Functions/
      read_file
      import_module
    Plan Functions/ # (doesn't have to be exploded but current Plan doesn't make it obvious that add_service will be there)
       add_service
       remove_service
```

**Comment by mieubrisse** [comment]
Hey @h4ck3rk3y can you add more color about what's going through your mind when you expand "Starlark Reference?"

**Comment by h4ck3rk3y** [comment]
For me the search now feels enough and haven't felt this pain in a while. Closing now, will open if someone needs this.
