### ISSUE TITLE
Validate port ID on services at validation, not execution

### ISSUE THREAD

**Issue by gbouv** [kurtosis-tech/kurtosis#474]
### Background & motivation

Right now, port IDs are not validated at all. So, whenever for example we trigger a request on a port_id for a service that doesn't exist, it fails once all previous isntrcutions have been executed.

This is something that could be easily validated before the execution starts

### Desired behaviour

Fail as early as possible when an unknown port_id is referenced for a given service

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by h4ck3rk3y** [comment]
Low hanging fruit thats nice othave
