### ISSUE TITLE
`wait` is waiting way longer than it should

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#477]
### What's your CLI version?

0.74.0

### Description & steps to reproduce

I've been periodically hitting cases where `wait` takes wayy too long to timeout. We just hit this in a quickstart user experience session (timeout = 5s, but the wait took 31s).

The tgz of `kurtosis dump` is on the feedback chann as "Dump from kurtosis quickstart exercise"

The impact is that users (myself included) are very confused as to what's happening.

### Desired behavior

`wait` times out when it should

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by victorcolombo** [comment]
@mieubrisse Do you have details on what was the `exec` or `request` being executed?

Right now `wait` does not interrupt an existing request/exec, instead if retries it as long as the total elapsed time is less than `timeout`, so if you have a very long request, it will at least try 1 time, that might exceed the timeout.

**Comment by mieubrisse** [comment]
ahhh, good call @victorcolombo . it was this step in the quickstart: https://docs.kurtosis.com/quickstart#run-postgres:~:text=to%20become%20available-,plan.wait(%0A%20%20%20%20%20%20%20%20service_name%20%3D%20%22api%22%2C%0A%20%20%20%20%20%20%20%20recipe%20%3D%20GetHttpRequestRecipe(%0A%20%20%20%20%20%20%20%20%20%20%20%20port_id%20%3D%20POSTGREST_PORT_ID%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20endpoint%20%3D%20%22/actor%3Flimit%3D5%22%2C%0A%20%20%20%20%20%20%20%20)%2C%0A%20%20%20%20%20%20%20%20field%20%3D%20%22code%22%2C%0A%20%20%20%20%20%20%20%20assertion%20%3D%20%22%3D%3D%22%2C%0A%20%20%20%20%20%20%20%20target_value%20%3D%20200%2C%0A%20%20%20%20%20%20%20%20timeout%20%3D%20%225s%22%2C%0A%20%20%20%20),-Now%2C%20run%20the

**Comment by mieubrisse** [comment]
you can see the full `kurtosis dump` output from the email the user sent to `feedback@`

**Comment by mieubrisse** [comment]
It seems like we should be using `context.WithTimeout` instead for this, right?

**Comment by victorcolombo** [comment]
I agree that this is the most intuitive behavior

**Comment by mieubrisse** [comment]
thanks @victorcolombo 🙏
