### ISSUE TITLE
[FR] Changing the version of the docs obstructs my view

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#487]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com

### Issue description

When choosing the version of the docs I wish to see, I have to use the drop-down bar. This is fine originally but with over 10+ older versions, the drop down bar gets quite big and obstructs my view. 

Is there something that can be done to periodically prune old versions (say, only keep the last 5 versions) to keep the drop down bar small, or add a scroll functionality to the drop down bar?

<img width="396" alt="image" src="https://user-images.githubusercontent.com/103802618/230745939-42c1e320-f64a-4b09-a077-0640d7b2defc.png">

**Comment by Peeeekay** [comment]
confirm with product that we only keep the minor versions. - @h4ck3rk3y
