### ISSUE TITLE
Small typo in quickstart? :) 

### ISSUE THREAD

**Issue by av-mido** [kurtosis-tech/kurtosis#547]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/quickstart/

### Issue description

I think there's a word missing in the quickstart? `What you've just seen is Kurtosis' powerful ability to data generated at runtime to set up service dependencies in multi-container test environments.`
`ability to data` should probably be `ability to use data`?

**Comment by leeederek** [comment]
Hey @av-mido! Good catch, thanks for letting us know! I've opened #548 to address this. Happy Sunday :) 

If you got other questions or need a hand, don't hesitate to reach out in [Discord](https://discord.gg/eBWFjGtm) or via more Github Issues! Thanks again!

**Comment by av-mido** [comment]
Thanks for the quick reply! It's not urgent :) I didn't notice the markdown files are in this repo, I could have edited it directly oops. thanks
