### ISSUE TITLE
CLI outputs errors

### ISSUE THREAD

**Issue by gabrielrussoc** [kurtosis-tech/kurtosis#563]
### What's your CLI version?

0.75.8

### Description & steps to reproduce

```
➜  ~ kt enclave ls
segment 2023/04/25 17:40:58 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2023/04/25 17:40:58 ERROR: 1 messages dropped because they failed to be sent and the client was closed
UUID           Name         Status     Creation Time
5dbe141b5d72   quickstart   RUNNING    Sat, 22 Apr 2023 18:24:16 CEST
```

### Desired behavior

no errors are printed

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by victorcolombo** [comment]
@gabrielrussoc Appreciate you filing this issue! 

I was able to repro this by blocking the outgoing connection to `api.segment.io`. That prints

```
segment 2023/04/27 14:16:02 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp 127.0.0.1:443: connect: connection refused
segment 2023/04/27 14:16:02 ERROR: 1 messages dropped because they failed to be sent and the client was closed
```

The root cause is that, by default, Segment output errors to `stderr`, that causes some confusion when mixed with our own logs.
