### ISSUE TITLE
`args` should be specifiable as YAML

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#581]
### Background & motivation

It's really, really annoying that I can only pass in JSON, because it doesn't allow me to comment my args. This becomes especially painful for large params, like the eth2-package

### Desired behaviour

`kurtosis run . "$(cat /tmp/params.yml)"` will work as expected

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by leoporoli** [comment]
ticket #578 is related but probably more complicated to implement, so we could start with this one first at least we define that 578 is a better solution and start with that

**Comment by mieubrisse** [comment]
Probably plays very nicely with #1112
