### ISSUE TITLE
brew install kurtosis-tech/tap/kurtosis-cli results in 404

### ISSUE THREAD

**Issue by aaronbuchwald** [kurtosis-tech/kurtosis#642]
### What's your CLI version?

na

### Description & steps to reproduce

aaronbuchwald@Aarons-MacBook-Pro-2 subnet-evm % brew install kurtosis-tech/tap/kurtosis-cli
==> Fetching kurtosis-tech/tap/kurtosis-cli
Error: kurtosis-cli: Failed to download resource "kurtosis-cli"
Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases/download/0.65.0/kurtosis-cli_0.65.0_darwin_amd64.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/2 404 
server: GitHub.com
date: Thu, 25 May 2023 19:09:45 GMT
content-type: text/plain; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'
content-length: 9
x-github-request-id: CEBC:6933:157D12:200377:646FB2AF

aaronbuchwald@Aarons-MacBook-Pro-2 subnet-evm % 

### Desired behavior

brew should be able to install kurtosis following directions here: https://docs.kurtosis.com/install#iii-optional-add-command-line-completion

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by aaronbuchwald** [comment]
Please let me know if there is a better place to move this GitHub issue

**Comment by leeederek** [comment]
Hi @aaronbuchwald this is indeed the right spot. I tried to reproduce the issue but I could not. Can you try: `brew update` before trying again?

**Comment by h4ck3rk3y** [comment]
Hey @aaronbuchwald! I am sorry you ran into this. Adding more color to what Derek said; I think the brew tap is out of date on your machine. 

We had open sourced Kurtosis around the middle of February and we had cleaned up some old versions of Kurtosis(versions prior to 0.66.8) in the process. Rest assured going forward all releases should be available.

As Derek said can you try the following

```bash
brew update
brew upgrade kurtosis-tech/tap/kurtosis-cli
```

If that doesn't work can we verify whether any pinned versions exist on brew and remove them if they do;

```
brew list --pinned
```

Make sure to restart Kurtosis after doing the upgrade. If you try running a package via the CLI we'll issue a restart anyway but we don't do so for any commands run via the `SDK`.

```
kurtosis engine restart
```

**Comment by h4ck3rk3y** [comment]
Had to run brew update a few times and a few brew tap repairs. Ran into the issue of moving from "master" to "main" for the tap. 

There was a misleading Xcode install prompt that threw us of but it just suggested it needs to be installed

Autocomplete was more work to setup than it should have been. Will create a separate ticket for that.
