### ISSUE TITLE
Fix the retry strategy problem on port wait feature

### ISSUE THREAD

**Issue by leoporoli** [kurtosis-tech/kurtosis#648]
### What's your CLI version?

0.76.3

### Description & steps to reproduce

The first request executed with the port wait feature hangs until the main timeout is reached and it doesn't let execute another scan port request. It happens because the scan port request timeout is equal to the port wait timeout and them should be different

### Desired behavior

Add a default retry value equal to 3, so the `scan-port-timeout = port-wait-timeout / 3` 

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by leoporoli** [comment]
This is done, right? @laurentluce

**Comment by laurentluce** [comment]
This is done in #653
