### ISSUE TITLE
WSL2 does not redirect to localhost

### ISSUE THREAD

**Issue by ericobi** [kurtosis-tech/kurtosis#671]
### What's your CLI version?

0.76.7

### Description & steps to reproduce

When I am running containers in my local or cloud, the ports are not redirecting to the localhost or 127.0.0.1

```
============ User Services =================

UUID           Name          Ports                                              Status

fd97db9a1002   mongodb       mongodb: 27017/tcp -> mongodb://127.0.0.1:32803    RUNNING

4ff9b3f4228e   novu_api      novu_api_port: 3000/tcp -> http://127.0.0.1:3000   RUNNING

8fd20e961c72   novu_embed    novu_embed: 4701/tcp -> http://127.0.0.1:4701      RUNNING

40bde6f5387c   novu_web      novu_web: 4200/tcp -> http://127.0.0.1:4200        RUNNING

ee7c041bc2e6   novu_widget   novu_widget: 4500/tcp -> http://127.0.0.1:32804    RUNNING

569d075ba341   novu_worker   <none>                                             RUNNING

9cb48000d596   novu_ws       novu_ws: 3002/tcp -> ws://127.0.0.1:3002           RUNNING

3d3a4a079e20   redis         client: 6379/tcp -> 127.0.0.1:32802                RUNNING

```

### Desired behavior

When I click the link, it should redirect localhost on my browser.

A temporary solution is: https://superuser.com/questions/1594420/cant-access-127-0-0-180-outside-of-wsl2-ubuntu-20-04

WSL2 uses a virtual network inside so it has an actual IP address on our network.
I was able to connect using that physical address.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by adschwartz** [comment]
Wanted to add a nuance to this problem: that while you can access the services via this virtual network (ip address) that WSL uses, it creates problems when using a browser to connect/access a web server. The web server will provide a URL for the services the client (browser) needs to access inside the enclave and will often use `localhost` as the hostname. This doesn't work if you instead have to access the services through the WSL virtual network interface.

One example of this failing is: novu-package

**Comment by mieubrisse** [comment]
Hey @ericobi , thanks for filing this - looking into this now!

@adschwartz , does this work in the browser if `127.0.0.1` is replaced with the IP of the WSL system?

**Comment by adschwartz** [comment]
@mieubrisse Yes and no: we (@ericobi) was able to access the Novu application through the WSL virtual network adapter ip. Loading the page itself works fine, _but_ any interaction from that website with other parts of the system (like APIs, ws etc.) fails because the services expect each other to be accessible though a deterministic hostname (in this case `localhost` or `127.0.0.1` which does not match the WSL ip).

**Comment by leeederek** [comment]
Hey @ericobi - with the rollout of cloud.kurtosis.com, users can now visit our web-app to view and interact with enclaves created locally or in our cloud. Closing this now as we believe the new offering will enable you to perform this workflow (and more) in a cleaner way. Thank you!
