### ISSUE TITLE
add the ability to start containers with certain minimum resources

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#675]
### Background & motivation

While talking to AaronB from Avalanche last week he surfaced the need to start containers of Avax nodes with certain minimum resources. He referred to c5.large but what really wants to do is be able to say give me X gigabytes of RAM and Y cores of CPU. 

He wants to do this for throughput testing

### Desired behaviour

Ability to start containers with a certain minimum resources

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

**Comment by leeederek** [comment]
@h4ck3rk3y question for you: does he care about cloud provider-specific primitives (i.e. things he wants to verify against aws specifically)?

**Comment by h4ck3rk3y** [comment]
He doesn't care about cloud specific primitives like "c5.large"; I think he would like that API where you could just say "c5.large" and we parse out the memory/cpu; but what he really cares about

1. No resource contention between the containers that are spun up
2. Containers that are spun up have minimum resources that are configurable

**Comment by mieubrisse** [comment]
@h4ck3rk3y this is actually doable for memory & CPU already today: https://docs.kurtosis.com/starlark-reference/service-config#:~:text=Default%3A%20no%20limit)-,cpu_allocation,-%3D%201000%2C

Going to close this, but reopen if that doesn't fix!

**Comment by h4ck3rk3y** [comment]
@mieubrisse That isn't what I want. That at best sets "maximum"  resources I want to set "minimum" resources. I want a guarantee that the node I start has a certain minimum RAM/CPU and there's no resource contention

**Comment by mieubrisse** [comment]
Relevant notes for implementer: https://docs.docker.com/config/containers/resource_constraints/#configure-the-realtime-scheduler
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by mieubrisse** [comment]
@h4ck3rk3y Prototype:
```starlark
ServiceConfig(
    # The minimum amount of CPUs reserved for the service, in millicpu/millicore.
    # OPTIONAL (Default: none)
    min_cpu = 1000,

    # The minimum amount of memory, in megabytes, reserved for the service
    # OPTIONAL (Default: none)
    min_memory = 1024,

    # The maximum amount of CPUs the service can use, in millicpu/millicore.
    # OPTIONAL (Default: no limit)
    max_cpu = 1000,

    # The maximum amount of memory, in megabytes, the service can use.
    # OPTIONAL (Default: no limit)
    max_memory = 1024,
)
```

**Comment by h4ck3rk3y** [comment]
This works for me 👍 ! Does this guarantee no contention? I suppose it can on k8s but on Docker?

**Comment by mieubrisse** [comment]
Docker is a bit dicier; I did some preliminary investigation and I thiiiiink there's a way to do it but it's not guaranteed. Tagging in @Peeeekay who'll be doing implementation!

**Comment by h4ck3rk3y** [comment]
Can we possibly support minimum disk as well?

**Comment by mieubrisse** [comment]
Unfortunately not; neither Docker nor k8s support it AFAICT (and it makes sense why - you'd need to make a "how much size do you have available?" request to every volume driver on every Pod start)

**Comment by Peeeekay** [comment]
@h4ck3rk3y do we really need this for Docker? Because I would imagine something like kubernetes or docker-swarm to be responsible for making sure the container is with appropriate resources in a node - so having this for kubernetes should be good enough?

**Comment by gbouv** [comment]
Done by PK
