### ISSUE TITLE
add the ability to do execs in parallel

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#677]
### Background & motivation

subnets have this step where you do some transactions on the chain and then restart every node with a new flag `--tracked-subnets` if we go one by one this will take a long time

ideally we can do something like `killall avalanchego && ./avalnchego --` on all nodes in parallel

this might be related to @laurentluce 's stop/restart but the restart happens with different flags

### Desired behaviour

either the ability to stop and restart services with different arguments or

plan.exec_parallel({
      "service_name": ExecRecipe()
}
)

^ copying this design from current add_services

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

**Comment by h4ck3rk3y** [comment]
For now I'll try to use `&` at the end of the exec to execute in parallel; I might lose the ability to check the exit code but thats my workaround.

**Comment by h4ck3rk3y** [comment]
Adding more context. I want to be able to start 100 nodes to demo to AVAX. Aaron wants that to be in order of a few minutes. If we are doing the execs sequentially its going to take a while. I haven't tried the `&` approach yet to have enough data on whether it works.

Ideally I demo 100 nodes a week from now but i haven't run the full loop to figure out what the constraints are but this does seem like one!

**Comment by h4ck3rk3y** [comment]
https://github.com/kurtosis-tech/avalanche-package/blob/main/src/node_launcher.star#L81-L87
avax needed 100 nodes to be started in < 10 mintues
so to start the binary i had to find this weird combination of
/bin/sh -c nohup command_to_run > /dev/null 2>&1 &
this took me a while to discover
as i ran through iterations of /bin/sh with &, then /bin/sh with nohup &, then adding /dev/null
in the middle i tried to eliminate bin sh a few times
but this took hours, had to loop in victor,
so ideally running a bunch in background parallely is nice
for now I run it using & and then assert health on the last node
as i am not guaranteed that the nohup/&/bin sh wrapped thing has finished
so an api to - run multiple execs in parallel on different services in the background and waiting for them to finish is great a brownie point would be something like
execs["node-1] = [
  "mkdir parent",
  "touch parent/foo.txt",
  "echo parent/foo.rxt"
]
i.e run few commands sequentially per node but parallel across nodes
but i can achieve that by concatenating them with && so I don't thing its super necessary
like if i could do that then i'd wrap https://github.com/kurtosis-tech/avalanche-package/blob/main/src/node_launcher.star#L110-L131 the following in that new exec

**Comment by mieubrisse** [comment]
Closing this; if this comes up again, I would implement it via DAG-plan (not via a `plan` command to run multiple exec's)
