### ISSUE TITLE
Kurtosis shell exec does not return the return value of command

### ISSUE THREAD

**Issue by victorcolombo** [kurtosis-tech/kurtosis#688]
### What's your CLI version?

0.77.0

### Description & steps to reproduce

```
$ kurtosis enclave add --name test-enclave
$ kurtosis service add test-enclave test2 httpd --ports http=80
$ kurtosis service shell test-enclave test2 --exec "exit 1"
echo $? # prints 0
```

This is critical for usage in CI systems that check exit code to report failure

### Desired behavior

`echo $?` should print 1

This behavior happens because we use `GetConnectionWithUserService` to act both as a attach terminal and as an exec with the param `commandToRunInsteadOfBash`. https://github.com/kurtosis-tech/kurtosis/blob/68a1ad1d9ed9b6d9abdd1fcebc9bb30d8ec37af9/container-engine-lib/lib/backend_interface/kurtosis_backend.go#L271

I believe `GetConnectionWithUserService` should be reserved for interactive operations, since we are attaching a connection. So getting an interactive shell or even some interactive programs like `cat` (equivalent to `-it` flag in Docker)

For non interactive ones, like `echo`, could simply use `RunUserServiceExecCommands` when running `kurtosis service shell ... --exec ...`, since that command and blocking, and returns all information about the program execution (return status), but does not offer interactivity (maybe `kurtosis service exec` to match Dockers terminology?)

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by gbouv** [comment]
Adding `kurtosis service exec` in #690
