### ISSUE TITLE
`kurtosis files download` doesn't tab-complete the artifact name

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#766]
### What's your CLI version?

0.80.0

### Description & steps to reproduce

1. Create an enclave with a files artifact inside
2. Try to download the files artifact by doing `kurtosis files download the-enclave` and tab-completing the artifact name

### Desired behavior

Tab-completion on the artifact name works

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by Peeeekay** [comment]
@laurentluce will sync up with @mieubrisse regarding this ticket.
