### ISSUE TITLE
Link out to Kuberentes Docs from the Running in Kubernetes page in docs.kurtosis.com

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#801]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/k8s/#i-create-a-kubernetes-cluster

### Issue description

> ...but linking to some official k8s docs on the running kurtosis in k8s would be helpful

AaronB was trying to run Kurtosis with Kubernetes over the weekend and was running into issues.

**Comment by mieubrisse** [comment]
@h4ck3rk3y what's the concrete action, and can @thylocine33 help here? I see that there's at least one link to the official k8s docs on that page

**Comment by h4ck3rk3y** [comment]
She just added it today. Closing this.
