### ISSUE TITLE
Typo in "WWith"

### ISSUE THREAD

**Issue by F4ever** [kurtosis-tech/kurtosis#832]
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/how-to-local-eth-testnet#configure-hardhat-to-use-the-local-testnet

### Issue description

WWith -> With

![image](https://github.com/kurtosis-tech/kurtosis/assets/27773025/da32eb32-7a64-4aae-a84a-7e52da3fdea1)

**Comment by leeederek** [comment]
Thanks @F4ever! Will fix shortly.
