### ISSUE TITLE
`upload_files` fails if it hits a symlink

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#846]
### What's your CLI version?

0.80.6

### Description & steps to reproduce

I had a Bazel project directory which has symlinks `bazel-bin`, `bazel-out`, etc. inside.

I tried calling `plan.upload_files` on this directory, but it failed with:
```
There was an error executing Starlark code
An error occurred executing instruction (number 1) at github.com/foo/bar[3:40]:
  upload_files(src="github.com/foo/bar/workspace")
  Caused by: An error occurred while compressing the files '/kurtosis-data/startosis-packages/foo/bar/workspace'
  Caused by: Failed to compress '/kurtosis-data/startosis-packages/foo/bar/workspace'.
  Caused by: walking /kurtosis-data/startosis-packages/foo/bar/workspace/bazel-bin: /kurtosis-data/startosis-packages/foo/bar/workspace/bazel-bin: stat: stat /kurtosis-data/startosis-packages/foo/bar/workspace/bazel-bin: no such file or directory

Error encountered running Starlark code.
```

### Desired behavior

Symlinks don't choke `plan.upload_files`

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by mieubrisse** [comment]
Here's a test package demonstrating the behaviour:
[symlink.zip](https://github.com/kurtosis-tech/kurtosis/files/12083508/symlink.zip)

**Comment by leoporoli** [comment]
@mieubrisse ok, first thing I found: this error is not related to the `upload_files` instruction, it's related to what happens with symlinks files when a package is copied into the enclave's volume.

This is the symlink `new-symlink` link in the host machine
```
dir ❯ ls -l
lrwxr-xr-x  1 lporoli  staff  8 Jul 18 14:53 new-symlink -> file.txt
```

And this is the same symlink in the `kurtosis-data` folder inside the enclave's volume
```
/kurtosis-data/startosis-packages/foo/bar/dir # ls -l
lrwxrwxrwx    1 root     root            15 Jul 18 18:21 new-symlink -> dir/new-symlink
```

We can see that the symlink in the enclave's volume has a wrong link.

I'll continue exploring what is modifying it
