### ISSUE TITLE
[BUG] When viewing a service in the frontend, there is no way for me to return to the enclave view 

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#872]
### Background & motivation

<img width="3007" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/31c63034-7e89-43f1-b8f5-b4579f2f6efb">

After I click on a service in the UI, I cannot "go back" to see my enclave. The workaround now is to press "BACK" in my browser, which is not great.

### Desired behaviour

There is a button in the UI that says "return to enclave view" from the service view

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by Peeeekay** [comment]
improved the navigation.

**Comment by Peeeekay** [comment]
https://github.com/kurtosis-tech/kurtosis/pull/940 as per this PR.
