### ISSUE TITLE
[FR] Improve the log line user experience when viewing a service

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#873]
### Background & motivation

When viewing a service, the logs are shown to me in the UI (which is great) but the most recent logs are all at the bottom, meaning I have to scroll all the way down to see the most recent log lines. I believe for a dev-workflow, it would be valuable to me to see the most recent logs up front and center by default. As a nice to have, i'd love to see the sorting toggle-able too and filter-able.

<img width="2478" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/103802618/f784fc4b-6b20-48fa-9cce-1f00716e68a8">

### Desired behaviour

1. I would like the logs to be sorted by MOST RECENT to LEAST RECENT by default when viewing a service
2. I would also like the ability to filter for specific WARN or INFO logs only & 
3. be able to toggle the sorting as well

This, in my opinion, is ranked from most desired to least desired

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by mieubrisse** [comment]
Strongly believe we shouldn't reverse-sort as this will confuse anyone that gets a copy-pasted output, but what we _should_ do is automatically jump to & stick to the bottom (that seems to be the commonly-accepted way to do this)

**Comment by Peeeekay** [comment]
@leeederek this ticket seems to be many sub tickets.. I will go with approach kevin suggested on -- instead of supporting scroll down -- users will be shown the last log entries first and can scroll up. Will add ( support for showing only warn, info, error logs in as a different issue)

**Comment by mieubrisse** [comment]
Now implemented
