### ISSUE TITLE
[FR] Add an optional email-share flow/option upon Kurtosis install and upgrade in the CLI

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#895]
### Background & motivation

We want to curate an email list for us to push content to engaged Kurtosis users with. I'd like to have this in the product itself. 

### Desired behaviour

This Github issue tracks two related things (the first one is more important):
1.  Add functionality such that when someone installs Kurtosis for the first time, they are prompted to optionally share their email with us
2. Upon upgrade at a certain version (that we mandate one-time, or maybe periodically), we prompt the user to share their email (optionally)

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by gbouv** [comment]
Need to figure out how important that is

**Comment by mieubrisse** [comment]
@leeederek can you comment?

**Comment by h4ck3rk3y** [comment]
@mieubrisse i talked with Galen. Will attempt to have this done in the first half of my day tomorrow.
