### ISSUE TITLE
Increase IP range of subnetworks

### ISSUE THREAD

**Issue by victorcolombo** [kurtosis-tech/kurtosis#912]
### Background & motivation

Right now the range of services is too narrow. This is due to some corner cutting on the code that assign IPs to enclaves.

### Desired behaviour

Increase the range, making a tighter calculation of IP bits

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by mieubrisse** [comment]
@victorcolombo can you add more context on this? my understanding is that we're allocating some Really Large number of IPs per network (I think 4096) and they should all be usable

**Comment by victorcolombo** [comment]
Weaviate uses HashiCorp/Memberlist which uses go-sockaddr to get the ["](https://github.com/hashicorp/memberlist/blob/e5eb6d78d6f23ad6ee996966b5c6c3f116f1b510/net_transport.go)[private ip](https://github.com/hashicorp/memberlist/blob/e5eb6d78d6f23ad6ee996966b5c6c3f116f1b510/net_transport.go#L160)["](https://github.com/hashicorp/memberlist/blob/e5eb6d78d6f23ad6ee996966b5c6c3f116f1b510/net_transport.go).

This private IP address range is defined by RFC 6890 which calls `10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16` private ip address ranges.

Docker compose tends to handout ip addresses from this range while Kurtosis used to pick anything that works like 6.5.2.3 (which isn't a private ip address).

The HashiCorp code guards against this; and wants the user to pass in a flag to override this private ip address behavior (for security I am guessing). We don't own Weaviate code so we can't pass in the flag that allows the override & random Docker images should work on KT without a lot of tweaking.

Unfortunately `10.0.0.0/8` causes problems with Circle, a use case we want to support.

**Comment by victorcolombo** [comment]
For ease of implementation, we restricted ourselves to the `172.16.0.0/12` range, picking third for enclave addressing and bits for service addressing. This is very loose, so I'm tightening this up with https://github.com/kurtosis-tech/kurtosis/pull/919.
