### ISSUE TITLE
log output fails to update when switching between services in the kurtosis frontend

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#921]
### What's your CLI version?

0.80.9

### Description & steps to reproduce

I cannot view logs by service in the frontend - navigating between services doesn't update the logs shown in the UI.

https://www.loom.com/share/b382e4d307f24516a8d4a58e9fa7d18b

### Desired behavior

When navigating from ServiceA to ServiceB, I expect the log output for each service to change from logs for ServiceA to logs for ServiceB. 

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by Peeeekay** [comment]
@leeederek  discussed offline; this is working. The browser was caching the older version;; i have not observed the behaviour recently - but tracking it!
