### ISSUE TITLE
Throw an error when the user is trying to run a package with less than the minimum resources available.

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#925]
### Background & motivation

We've hit the "the user's Docker settings are too low" issue many times now, and we now have `min_memory` and `min_cpu` available in ServiceConfig. We should proactively error to the user when they're trying to run with too little resources.

### Desired behaviour

For the Docker backend, if the user is trying to run a package whose minimum resource requirements at any point in the plan are greater than what's free in the Docker engine, proactively throw an error to the user telling them the problem and how they can fix it.

NOTE: this requires doing bookkeeping and walking through each step in the plan! It's not enough to just add everything up (because the user might remove services too)

- TODO in the code to make this more intelligent, taking into account the resource requirements of ALL the enclaves
- TODO in the appropriate spot in the Kubernetes backend to do the same

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by h4ck3rk3y** [comment]
Done :)
