### ISSUE TITLE
`kurtosis web` should take the user to `localhost:9711/enclaves`

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#957]
### Background & motivation

`kurtosis web` requires an unnecessary click to 

### Desired behaviour

`kurtosis web` takes me straight to the enclaves page

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by Peeeekay** [comment]
it's should be merged and released.
