### ISSUE TITLE
Looking at logs for a long time via kurtosis seems to time out every now and then though.

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#969]
### What's your CLI version?

Unknown

### Description & steps to reproduce

Reported by @barnabasbusa on #934 

### Desired behavior

Users should be able to look at logs for Kurtosis for at least a day or more

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

**Comment by gbouv** [comment]
Try on eth package and tail the logs of the EL/CL client

**Comment by gbouv** [comment]
Yup, I was able to narrow down the problem. It's the docker client timeout. Log streaming will stop after the timeout has elapsed. We have a similar issue when downloading images via the docker client as well. Very large image causes a timeout on the docker client b/c it takes longer than the timeout to download.
Maybe we shouldn't use timeout at all for those kind of request. I'll continue digging

**Comment by barnabasbusa** [comment]
if you enable `-f` with `service logs`, then there should be no timeout. 
For downloading images I feel like a 300-600s timeout is appropriate.
