### ISSUE TITLE
Remove all enclaves with a single command.

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#974]
### Background & motivation

It would be great to be able to remove all running enclaves instead of doing it one by one.

### Desired behaviour

Have a flag or option to take more than one arg for 
For example:
`kurtosis enclave rm -f <enclaveName1> <enclaveName2> ... <enclaveName100>` (with tab complete support)
or 
`kurtosis enclave rm -f --all-enclaves`

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

**Comment by gbouv** [comment]
Hey @barnabasbusa!
What about using `kurtosis clean -a`? This removes all enclaves, running or stopped. It basically leaves only the kurtosis engine running. 
Would that help or are you looking for something more specific?

It's true that we don't have a way to remove multiple named enclave in one command. We could easily make `kurtosis enclave rm` greedy though, enabling something like `kurtosis enclave rm enclave-1 enclave-2 enclave-3`

**Comment by barnabasbusa** [comment]
Ah didn't know `kurtosis clean` takes an arg.  In this case it makes sense. 

Would still be a good idea to enable the deletion of multiple enclaves in one command imho.

**Comment by gbouv** [comment]
Yup that feature makes sense to me, and AFAICT that's a quick fix so I'll submit a PR. Thanks for flagging :)
I'll keep this issue open until the PR is merged

**Comment by barnabasbusa** [comment]
Super nitpick but would it be possible to remove the already selected enclaves from the tab complete? 
E.g:
I have 3 enclaves:
`rustling-peak  winter-ocean  winter-peak`

I do `kurtosis rm -rf -f <tab>`
It lists all 3, then I select one with enter, then 
`kurtosis rm -rf -f rustling-peak <tab> `
it should return only 2 ( winter-ocean  winter-peak)  of the remaining items, instead of all 3 (`rustling-peak  winter-ocean  winter-peak`).
